plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev.legacyforge'
    id 'org.jetbrains.kotlin.jvm'
}

legacyForge {
    apply plugin: 'org.jetbrains.kotlin.jvm'
    apply plugin: 'kotlin'
    version = "${minecraft_version}-${forge_version}"


    // AT validation is broken on Forge 1.20.1
    validateAccessTransformers = false

    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers = ["src/main/resources/META-INF/accesstransformer.cfg"]
    }

    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }

    sourceSets {
        main.kotlin.srcDirs = ['src/main/java', 'src/main/kotlin']
    }

    compileKotlin {
        source(project(":common").sourceSets.main.kotlin)
        inputs.file "../gradle.properties"
    }

    runs {
        client {
            client()
        }
        data {
            data()
            programArguments.addAll '--mod', 'hybrid_blocks', '--all',
                    '--output', file('src/generated/resources/').getAbsolutePath(),
                    '--existing', file('src/main/resources/').getAbsolutePath(),
                    '--existing', file('src/generated/fabric/resources/').getAbsolutePath()
        }
        server {
            server()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

repositories {
    maven {
        name = 'Kotlin for Forge'
        url = 'https://thedarkcolour.github.io/KotlinForForge/'
    }
    mavenCentral()
}

sourceSets.main.resources.srcDirs += project(':fabric').file("src/generated/resources")
sourceSets.main.java.srcDirs += project(":common").file('src/main/java')

dependencies {
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.5.0"))
    annotationProcessor("org.spongepowered:mixin:0.8.5-SNAPSHOT:processor")
    implementation 'org.jetbrains:annotations:25.0.0'
    implementation 'thedarkcolour:kotlinforforge:4.11.0'
    implementation(jarJar("io.github.llamalad7:mixinextras-forge:0.5.0"))
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'org.jetbrains.kotlin.jvm'
    apply plugin: 'kotlin'
    repositories {
        mavenCentral()
    }
}