package dev.hybridlabs.blocks.block

import net.minecraft.data.family.BlockFamilies

object HybridBlocksFamilies {

    val WHITE_BRICKS = BlockFamilies.register(HybridBlocksBlocks.WHITE_BRICKS)
        .stairs(HybridBlocksBlocks.WHITE_BRICK_STAIRS)
        .slab(HybridBlocksBlocks.WHITE_BRICK_SLAB)
        .wall(HybridBlocksBlocks.WHITE_BRICK_WALL)
        .cracked(HybridBlocksBlocks.CRACKED_WHITE_BRICKS)
        .build()

    val ORANGE_BRICKS = BlockFamilies.register(HybridBlocksBlocks.ORANGE_BRICKS)
        .stairs(HybridBlocksBlocks.ORANGE_BRICK_STAIRS)
        .slab(HybridBlocksBlocks.ORANGE_BRICK_SLAB)
        .wall(HybridBlocksBlocks.ORANGE_BRICK_WALL)
        .cracked(HybridBlocksBlocks.CRACKED_ORANGE_BRICKS)
        .build()

    val MAGENTA_BRICKS = BlockFamilies.register(HybridBlocksBlocks.MAGENTA_BRICKS)
        .stairs(HybridBlocksBlocks.MAGENTA_BRICK_STAIRS)
        .slab(HybridBlocksBlocks.MAGENTA_BRICK_SLAB)
        .wall(HybridBlocksBlocks.MAGENTA_BRICK_WALL)
        .cracked(HybridBlocksBlocks.CRACKED_MAGENTA_BRICKS)
        .build()

    val LIGHT_BLUE_BRICKS = BlockFamilies.register(HybridBlocksBlocks.LIGHT_BLUE_BRICKS)
        .stairs(HybridBlocksBlocks.LIGHT_BLUE_BRICK_STAIRS)
        .slab(HybridBlocksBlocks.LIGHT_BLUE_BRICK_SLAB)
        .wall(HybridBlocksBlocks.LIGHT_BLUE_BRICK_WALL)
        .cracked(HybridBlocksBlocks.CRACKED_LIGHT_BLUE_BRICKS)
        .build()

    val YELLOW_BRICKS = BlockFamilies.register(HybridBlocksBlocks.YELLOW_BRICKS)
        .stairs(HybridBlocksBlocks.YELLOW_BRICK_STAIRS)
        .slab(HybridBlocksBlocks.YELLOW_BRICK_SLAB)
        .wall(HybridBlocksBlocks.YELLOW_BRICK_WALL)
        .cracked(HybridBlocksBlocks.CRACKED_YELLOW_BRICKS)
        .build()

    val LIME_BRICKS = BlockFamilies.register(HybridBlocksBlocks.LIME_BRICKS)
        .stairs(HybridBlocksBlocks.LIME_BRICK_STAIRS)
        .slab(HybridBlocksBlocks.LIME_BRICK_SLAB)
        .wall(HybridBlocksBlocks.LIME_BRICK_WALL)
        .cracked(HybridBlocksBlocks.CRACKED_LIME_BRICKS)
        .build()

    val PINK_BRICKS = BlockFamilies.register(HybridBlocksBlocks.PINK_BRICKS)
        .stairs(HybridBlocksBlocks.PINK_BRICK_STAIRS)
        .slab(HybridBlocksBlocks.PINK_BRICK_SLAB)
        .wall(HybridBlocksBlocks.PINK_BRICK_WALL)
        .cracked(HybridBlocksBlocks.CRACKED_PINK_BRICKS)
        .build()

    val GRAY_BRICKS = BlockFamilies.register(HybridBlocksBlocks.GRAY_BRICKS)
        .stairs(HybridBlocksBlocks.GRAY_BRICK_STAIRS)
        .slab(HybridBlocksBlocks.GRAY_BRICK_SLAB)
        .wall(HybridBlocksBlocks.GRAY_BRICK_WALL)
        .cracked(HybridBlocksBlocks.CRACKED_GRAY_BRICKS)
        .build()

    val LIGHT_GRAY_BRICKS = BlockFamilies.register(HybridBlocksBlocks.LIGHT_GRAY_BRICKS)
        .stairs(HybridBlocksBlocks.LIGHT_GRAY_BRICK_STAIRS)
        .slab(HybridBlocksBlocks.LIGHT_GRAY_BRICK_SLAB)
        .wall(HybridBlocksBlocks.LIGHT_GRAY_BRICK_WALL)
        .cracked(HybridBlocksBlocks.CRACKED_LIGHT_GRAY_BRICKS)
        .build()

    val CYAN_BRICKS = BlockFamilies.register(HybridBlocksBlocks.CYAN_BRICKS)
        .stairs(HybridBlocksBlocks.CYAN_BRICK_STAIRS)
        .slab(HybridBlocksBlocks.CYAN_BRICK_SLAB)
        .wall(HybridBlocksBlocks.CYAN_BRICK_WALL)
        .cracked(HybridBlocksBlocks.CRACKED_CYAN_BRICKS)
        .build()

    val PURPLE_BRICKS = BlockFamilies.register(HybridBlocksBlocks.PURPLE_BRICKS)
        .stairs(HybridBlocksBlocks.PURPLE_BRICK_STAIRS)
        .slab(HybridBlocksBlocks.PURPLE_BRICK_SLAB)
        .wall(HybridBlocksBlocks.PURPLE_BRICK_WALL)
        .cracked(HybridBlocksBlocks.CRACKED_PURPLE_BRICKS)
        .build()

    val BLUE_BRICKS = BlockFamilies.register(HybridBlocksBlocks.BLUE_BRICKS)
        .stairs(HybridBlocksBlocks.BLUE_BRICK_STAIRS)
        .slab(HybridBlocksBlocks.BLUE_BRICK_SLAB)
        .wall(HybridBlocksBlocks.BLUE_BRICK_WALL)
        .cracked(HybridBlocksBlocks.CRACKED_BLUE_BRICKS)
        .build()

    val BROWN_BRICKS = BlockFamilies.register(HybridBlocksBlocks.BROWN_BRICKS)
        .stairs(HybridBlocksBlocks.BROWN_BRICK_STAIRS)
        .slab(HybridBlocksBlocks.BROWN_BRICK_SLAB)
        .wall(HybridBlocksBlocks.BROWN_BRICK_WALL)
        .cracked(HybridBlocksBlocks.CRACKED_BROWN_BRICKS)
        .build()

    val GREEN_BRICKS = BlockFamilies.register(HybridBlocksBlocks.GREEN_BRICKS)
        .stairs(HybridBlocksBlocks.GREEN_BRICK_STAIRS)
        .slab(HybridBlocksBlocks.GREEN_BRICK_SLAB)
        .wall(HybridBlocksBlocks.GREEN_BRICK_WALL)
        .cracked(HybridBlocksBlocks.CRACKED_GREEN_BRICKS)
        .build()

    val RED_BRICKS = BlockFamilies.register(HybridBlocksBlocks.RED_BRICKS)
        .stairs(HybridBlocksBlocks.RED_BRICK_STAIRS)
        .slab(HybridBlocksBlocks.RED_BRICK_SLAB)
        .wall(HybridBlocksBlocks.RED_BRICK_WALL)
        .cracked(HybridBlocksBlocks.CRACKED_RED_BRICKS)
        .build()

    val BLACK_BRICKS = BlockFamilies.register(HybridBlocksBlocks.BLACK_BRICKS)
        .stairs(HybridBlocksBlocks.BLACK_BRICK_STAIRS)
        .slab(HybridBlocksBlocks.BLACK_BRICK_SLAB)
        .wall(HybridBlocksBlocks.BLACK_BRICK_WALL)
        .cracked(HybridBlocksBlocks.CRACKED_BLACK_BRICKS)
        .build()


    val CRACKED_BRICKS = BlockFamilies.register(HybridBlocksBlocks.CRACKED_BRICKS)
        .stairs(HybridBlocksBlocks.CRACKED_BRICK_STAIRS)
        .slab(HybridBlocksBlocks.CRACKED_BRICK_SLAB)
        .wall(HybridBlocksBlocks.CRACKED_BRICK_WALL)
        .build()

    val MOSSY_BRICKS = BlockFamilies.register(HybridBlocksBlocks.MOSSY_BRICKS)
        .stairs(HybridBlocksBlocks.MOSSY_BRICK_STAIRS)
        .slab(HybridBlocksBlocks.MOSSY_BRICK_SLAB)
        .wall(HybridBlocksBlocks.MOSSY_BRICK_WALL)
        .build()

    val MOSSY_WHITE_BRICKS = BlockFamilies.register(HybridBlocksBlocks.MOSSY_WHITE_BRICKS)
        .stairs(HybridBlocksBlocks.MOSSY_WHITE_BRICK_STAIRS)
        .slab(HybridBlocksBlocks.MOSSY_WHITE_BRICK_SLAB)
        .wall(HybridBlocksBlocks.MOSSY_WHITE_BRICK_WALL)
        .build()

    val MOSSY_ORANGE_BRICKS = BlockFamilies.register(HybridBlocksBlocks.MOSSY_ORANGE_BRICKS)
        .stairs(HybridBlocksBlocks.MOSSY_ORANGE_BRICK_STAIRS)
        .slab(HybridBlocksBlocks.MOSSY_ORANGE_BRICK_SLAB)
        .wall(HybridBlocksBlocks.MOSSY_ORANGE_BRICK_WALL)
        .build()

    val MOSSY_MAGENTA_BRICKS = BlockFamilies.register(HybridBlocksBlocks.MOSSY_MAGENTA_BRICKS)
        .stairs(HybridBlocksBlocks.MOSSY_MAGENTA_BRICK_STAIRS)
        .slab(HybridBlocksBlocks.MOSSY_MAGENTA_BRICK_SLAB)
        .wall(HybridBlocksBlocks.MOSSY_MAGENTA_BRICK_WALL)
        .build()

    val MOSSY_LIGHT_BLUE_BRICKS = BlockFamilies.register(HybridBlocksBlocks.MOSSY_LIGHT_BLUE_BRICKS)
        .stairs(HybridBlocksBlocks.MOSSY_LIGHT_BLUE_BRICK_STAIRS)
        .slab(HybridBlocksBlocks.MOSSY_LIGHT_BLUE_BRICK_SLAB)
        .wall(HybridBlocksBlocks.MOSSY_LIGHT_BLUE_BRICK_WALL)
        .build()

    val MOSSY_YELLOW_BRICKS = BlockFamilies.register(HybridBlocksBlocks.MOSSY_YELLOW_BRICKS)
        .stairs(HybridBlocksBlocks.MOSSY_YELLOW_BRICK_STAIRS)
        .slab(HybridBlocksBlocks.MOSSY_YELLOW_BRICK_SLAB)
        .wall(HybridBlocksBlocks.MOSSY_YELLOW_BRICK_WALL)
        .build()

    val MOSSY_LIME_BRICKS = BlockFamilies.register(HybridBlocksBlocks.MOSSY_LIME_BRICKS)
        .stairs(HybridBlocksBlocks.MOSSY_LIME_BRICK_STAIRS)
        .slab(HybridBlocksBlocks.MOSSY_LIME_BRICK_SLAB)
        .wall(HybridBlocksBlocks.MOSSY_LIME_BRICK_WALL)
        .build()

    val MOSSY_PINK_BRICKS = BlockFamilies.register(HybridBlocksBlocks.MOSSY_PINK_BRICKS)
        .stairs(HybridBlocksBlocks.MOSSY_PINK_BRICK_STAIRS)
        .slab(HybridBlocksBlocks.MOSSY_PINK_BRICK_SLAB)
        .wall(HybridBlocksBlocks.MOSSY_PINK_BRICK_WALL)
        .build()

    val MOSSY_GRAY_BRICKS = BlockFamilies.register(HybridBlocksBlocks.MOSSY_GRAY_BRICKS)
        .stairs(HybridBlocksBlocks.MOSSY_GRAY_BRICK_STAIRS)
        .slab(HybridBlocksBlocks.MOSSY_GRAY_BRICK_SLAB)
        .wall(HybridBlocksBlocks.MOSSY_GRAY_BRICK_WALL)
        .build()

    val MOSSY_LIGHT_GRAY_BRICKS = BlockFamilies.register(HybridBlocksBlocks.MOSSY_LIGHT_GRAY_BRICKS)
        .stairs(HybridBlocksBlocks.MOSSY_LIGHT_GRAY_BRICK_STAIRS)
        .slab(HybridBlocksBlocks.MOSSY_LIGHT_GRAY_BRICK_SLAB)
        .wall(HybridBlocksBlocks.MOSSY_LIGHT_GRAY_BRICK_WALL)
        .build()

    val MOSSY_CYAN_BRICKS = BlockFamilies.register(HybridBlocksBlocks.MOSSY_CYAN_BRICKS)
        .stairs(HybridBlocksBlocks.MOSSY_CYAN_BRICK_STAIRS)
        .slab(HybridBlocksBlocks.MOSSY_CYAN_BRICK_SLAB)
        .wall(HybridBlocksBlocks.MOSSY_CYAN_BRICK_WALL)
        .build()

    val MOSSY_PURPLE_BRICKS = BlockFamilies.register(HybridBlocksBlocks.MOSSY_PURPLE_BRICKS)
        .stairs(HybridBlocksBlocks.MOSSY_PURPLE_BRICK_STAIRS)
        .slab(HybridBlocksBlocks.MOSSY_PURPLE_BRICK_SLAB)
        .wall(HybridBlocksBlocks.MOSSY_PURPLE_BRICK_WALL)
        .build()

    val MOSSY_BLUE_BRICKS = BlockFamilies.register(HybridBlocksBlocks.MOSSY_BLUE_BRICKS)
        .stairs(HybridBlocksBlocks.MOSSY_BLUE_BRICK_STAIRS)
        .slab(HybridBlocksBlocks.MOSSY_BLUE_BRICK_SLAB)
        .wall(HybridBlocksBlocks.MOSSY_BLUE_BRICK_WALL)
        .build()

    val MOSSY_BROWN_BRICKS = BlockFamilies.register(HybridBlocksBlocks.MOSSY_BROWN_BRICKS)
        .stairs(HybridBlocksBlocks.MOSSY_BROWN_BRICK_STAIRS)
        .slab(HybridBlocksBlocks.MOSSY_BROWN_BRICK_SLAB)
        .wall(HybridBlocksBlocks.MOSSY_BROWN_BRICK_WALL)
        .build()

    val MOSSY_GREEN_BRICKS = BlockFamilies.register(HybridBlocksBlocks.MOSSY_GREEN_BRICKS)
        .stairs(HybridBlocksBlocks.MOSSY_GREEN_BRICK_STAIRS)
        .slab(HybridBlocksBlocks.MOSSY_GREEN_BRICK_SLAB)
        .wall(HybridBlocksBlocks.MOSSY_GREEN_BRICK_WALL)
        .build()

    val MOSSY_RED_BRICKS = BlockFamilies.register(HybridBlocksBlocks.MOSSY_RED_BRICKS)
        .stairs(HybridBlocksBlocks.MOSSY_RED_BRICK_STAIRS)
        .slab(HybridBlocksBlocks.MOSSY_RED_BRICK_SLAB)
        .wall(HybridBlocksBlocks.MOSSY_RED_BRICK_WALL)
        .build()

    val MOSSY_BLACK_BRICKS = BlockFamilies.register(HybridBlocksBlocks.MOSSY_BLACK_BRICKS)
        .stairs(HybridBlocksBlocks.MOSSY_BLACK_BRICK_STAIRS)
        .slab(HybridBlocksBlocks.MOSSY_BLACK_BRICK_SLAB)
        .wall(HybridBlocksBlocks.MOSSY_BLACK_BRICK_WALL)
        .build()

    val WHITE_QUARTZ = BlockFamilies.register(HybridBlocksBlocks.WHITE_QUARTZ)
        .stairs(HybridBlocksBlocks.WHITE_QUARTZ_STAIRS)
        .slab(HybridBlocksBlocks.WHITE_QUARTZ_SLAB)
        .build()

    val ORANGE_QUARTZ = BlockFamilies.register(HybridBlocksBlocks.ORANGE_QUARTZ)
        .stairs(HybridBlocksBlocks.ORANGE_QUARTZ_STAIRS)
        .slab(HybridBlocksBlocks.ORANGE_QUARTZ_SLAB)
        .build()

    val MAGENTA_QUARTZ = BlockFamilies.register(HybridBlocksBlocks.MAGENTA_QUARTZ)
        .stairs(HybridBlocksBlocks.MAGENTA_QUARTZ_STAIRS)
        .slab(HybridBlocksBlocks.MAGENTA_QUARTZ_SLAB)
        .build()

    val LIGHT_BLUE_QUARTZ = BlockFamilies.register(HybridBlocksBlocks.LIGHT_BLUE_QUARTZ)
        .stairs(HybridBlocksBlocks.LIGHT_BLUE_QUARTZ_STAIRS)
        .slab(HybridBlocksBlocks.LIGHT_BLUE_QUARTZ_SLAB)
        .build()

    val YELLOW_QUARTZ = BlockFamilies.register(HybridBlocksBlocks.YELLOW_QUARTZ)
        .stairs(HybridBlocksBlocks.YELLOW_QUARTZ_STAIRS)
        .slab(HybridBlocksBlocks.YELLOW_QUARTZ_SLAB)
        .build()

    val LIME_QUARTZ = BlockFamilies.register(HybridBlocksBlocks.LIME_QUARTZ)
        .stairs(HybridBlocksBlocks.LIME_QUARTZ_STAIRS)
        .slab(HybridBlocksBlocks.LIME_QUARTZ_SLAB)
        .build()

    val PINK_QUARTZ = BlockFamilies.register(HybridBlocksBlocks.PINK_QUARTZ)
        .stairs(HybridBlocksBlocks.PINK_QUARTZ_STAIRS)
        .slab(HybridBlocksBlocks.PINK_QUARTZ_SLAB)
        .build()

    val GRAY_QUARTZ = BlockFamilies.register(HybridBlocksBlocks.GRAY_QUARTZ)
        .stairs(HybridBlocksBlocks.GRAY_QUARTZ_STAIRS)
        .slab(HybridBlocksBlocks.GRAY_QUARTZ_SLAB)
        .build()

    val LIGHT_GRAY_QUARTZ = BlockFamilies.register(HybridBlocksBlocks.LIGHT_GRAY_QUARTZ)
        .stairs(HybridBlocksBlocks.LIGHT_GRAY_QUARTZ_STAIRS)
        .slab(HybridBlocksBlocks.LIGHT_GRAY_QUARTZ_SLAB)
        .build()

    val CYAN_QUARTZ = BlockFamilies.register(HybridBlocksBlocks.CYAN_QUARTZ)
        .stairs(HybridBlocksBlocks.CYAN_QUARTZ_STAIRS)
        .slab(HybridBlocksBlocks.CYAN_QUARTZ_SLAB)
        .build()

    val PURPLE_QUARTZ = BlockFamilies.register(HybridBlocksBlocks.PURPLE_QUARTZ)
        .stairs(HybridBlocksBlocks.PURPLE_QUARTZ_STAIRS)
        .slab(HybridBlocksBlocks.PURPLE_QUARTZ_SLAB)
        .build()

    val BLUE_QUARTZ = BlockFamilies.register(HybridBlocksBlocks.BLUE_QUARTZ)
        .stairs(HybridBlocksBlocks.BLUE_QUARTZ_STAIRS)
        .slab(HybridBlocksBlocks.BLUE_QUARTZ_SLAB)
        .build()

    val BROWN_QUARTZ = BlockFamilies.register(HybridBlocksBlocks.BROWN_QUARTZ)
        .stairs(HybridBlocksBlocks.BROWN_QUARTZ_STAIRS)
        .slab(HybridBlocksBlocks.BROWN_QUARTZ_SLAB)
        .build()

    val GREEN_QUARTZ = BlockFamilies.register(HybridBlocksBlocks.GREEN_QUARTZ)
        .stairs(HybridBlocksBlocks.GREEN_QUARTZ_STAIRS)
        .slab(HybridBlocksBlocks.GREEN_QUARTZ_SLAB)
        .build()

    val RED_QUARTZ = BlockFamilies.register(HybridBlocksBlocks.RED_QUARTZ)
        .stairs(HybridBlocksBlocks.RED_QUARTZ_STAIRS)
        .slab(HybridBlocksBlocks.RED_QUARTZ_SLAB)
        .build()

    val BLACK_QUARTZ = BlockFamilies.register(HybridBlocksBlocks.BLACK_QUARTZ)
        .stairs(HybridBlocksBlocks.BLACK_QUARTZ_STAIRS)
        .slab(HybridBlocksBlocks.BLACK_QUARTZ_SLAB)
        .build()

    val WHITE_SMOOTH_QUARTZ = BlockFamilies.register(HybridBlocksBlocks.WHITE_SMOOTH_QUARTZ)
        .stairs(HybridBlocksBlocks.WHITE_SMOOTH_QUARTZ_STAIRS)
        .slab(HybridBlocksBlocks.WHITE_SMOOTH_QUARTZ_SLAB)
        .build()

    val ORANGE_SMOOTH_QUARTZ = BlockFamilies.register(HybridBlocksBlocks.ORANGE_SMOOTH_QUARTZ)
        .stairs(HybridBlocksBlocks.ORANGE_SMOOTH_QUARTZ_STAIRS)
        .slab(HybridBlocksBlocks.ORANGE_SMOOTH_QUARTZ_SLAB)
        .build()

    val MAGENTA_SMOOTH_QUARTZ = BlockFamilies.register(HybridBlocksBlocks.MAGENTA_SMOOTH_QUARTZ)
        .stairs(HybridBlocksBlocks.MAGENTA_SMOOTH_QUARTZ_STAIRS)
        .slab(HybridBlocksBlocks.MAGENTA_SMOOTH_QUARTZ_SLAB)
        .build()

    val LIGHT_BLUE_SMOOTH_QUARTZ = BlockFamilies.register(HybridBlocksBlocks.LIGHT_BLUE_SMOOTH_QUARTZ)
        .stairs(HybridBlocksBlocks.LIGHT_BLUE_SMOOTH_QUARTZ_STAIRS)
        .slab(HybridBlocksBlocks.LIGHT_BLUE_SMOOTH_QUARTZ_SLAB)
        .build()

    val YELLOW_SMOOTH_QUARTZ = BlockFamilies.register(HybridBlocksBlocks.YELLOW_SMOOTH_QUARTZ)
        .stairs(HybridBlocksBlocks.YELLOW_SMOOTH_QUARTZ_STAIRS)
        .slab(HybridBlocksBlocks.YELLOW_SMOOTH_QUARTZ_SLAB)
        .build()

    val LIME_SMOOTH_QUARTZ = BlockFamilies.register(HybridBlocksBlocks.LIME_SMOOTH_QUARTZ)
        .stairs(HybridBlocksBlocks.LIME_SMOOTH_QUARTZ_STAIRS)
        .slab(HybridBlocksBlocks.LIME_SMOOTH_QUARTZ_SLAB)
        .build()

    val PINK_SMOOTH_QUARTZ = BlockFamilies.register(HybridBlocksBlocks.PINK_SMOOTH_QUARTZ)
        .stairs(HybridBlocksBlocks.PINK_SMOOTH_QUARTZ_STAIRS)
        .slab(HybridBlocksBlocks.PINK_SMOOTH_QUARTZ_SLAB)
        .build()

    val GRAY_SMOOTH_QUARTZ = BlockFamilies.register(HybridBlocksBlocks.GRAY_SMOOTH_QUARTZ)
        .stairs(HybridBlocksBlocks.GRAY_SMOOTH_QUARTZ_STAIRS)
        .slab(HybridBlocksBlocks.GRAY_SMOOTH_QUARTZ_SLAB)
        .build()

    val LIGHT_GRAY_SMOOTH_QUARTZ = BlockFamilies.register(HybridBlocksBlocks.LIGHT_GRAY_SMOOTH_QUARTZ)
        .stairs(HybridBlocksBlocks.LIGHT_GRAY_SMOOTH_QUARTZ_STAIRS)
        .slab(HybridBlocksBlocks.LIGHT_GRAY_SMOOTH_QUARTZ_SLAB)
        .build()

    val CYAN_SMOOTH_QUARTZ = BlockFamilies.register(HybridBlocksBlocks.CYAN_SMOOTH_QUARTZ)
        .stairs(HybridBlocksBlocks.CYAN_SMOOTH_QUARTZ_STAIRS)
        .slab(HybridBlocksBlocks.CYAN_SMOOTH_QUARTZ_SLAB)
        .build()

    val PURPLE_SMOOTH_QUARTZ = BlockFamilies.register(HybridBlocksBlocks.PURPLE_SMOOTH_QUARTZ)
        .stairs(HybridBlocksBlocks.PURPLE_SMOOTH_QUARTZ_STAIRS)
        .slab(HybridBlocksBlocks.PURPLE_SMOOTH_QUARTZ_SLAB)
        .build()

    val BLUE_SMOOTH_QUARTZ = BlockFamilies.register(HybridBlocksBlocks.BLUE_SMOOTH_QUARTZ)
        .stairs(HybridBlocksBlocks.BLUE_SMOOTH_QUARTZ_STAIRS)
        .slab(HybridBlocksBlocks.BLUE_SMOOTH_QUARTZ_SLAB)
        .build()

    val BROWN_SMOOTH_QUARTZ = BlockFamilies.register(HybridBlocksBlocks.BROWN_SMOOTH_QUARTZ)
        .stairs(HybridBlocksBlocks.BROWN_SMOOTH_QUARTZ_STAIRS)
        .slab(HybridBlocksBlocks.BROWN_SMOOTH_QUARTZ_SLAB)
        .build()

    val GREEN_SMOOTH_QUARTZ = BlockFamilies.register(HybridBlocksBlocks.GREEN_SMOOTH_QUARTZ)
        .stairs(HybridBlocksBlocks.GREEN_SMOOTH_QUARTZ_STAIRS)
        .slab(HybridBlocksBlocks.GREEN_SMOOTH_QUARTZ_SLAB)
        .build()

    val RED_SMOOTH_QUARTZ = BlockFamilies.register(HybridBlocksBlocks.RED_SMOOTH_QUARTZ)
        .stairs(HybridBlocksBlocks.RED_SMOOTH_QUARTZ_STAIRS)
        .slab(HybridBlocksBlocks.RED_SMOOTH_QUARTZ_SLAB)
        .build()

    val BLACK_SMOOTH_QUARTZ = BlockFamilies.register(HybridBlocksBlocks.BLACK_SMOOTH_QUARTZ)
        .stairs(HybridBlocksBlocks.BLACK_SMOOTH_QUARTZ_STAIRS)
        .slab(HybridBlocksBlocks.BLACK_SMOOTH_QUARTZ_SLAB)
        .build()
}

