package dev.hybridlabs.blocks.block

import dev.hybridlabs.blocks.HybridBlocks
import net.fabricmc.fabric.api.`object`.builder.v1.block.FabricBlockSettings
import net.minecraft.block.*
import net.minecraft.registry.Registries
import net.minecraft.registry.Registry
import net.minecraft.util.DyeColor
import net.minecraft.util.Identifier

/**
 * All Hybrid Blocks blocks.
 */
object HybridBlocksBlocks {

    // region Quartz

    val WHITE_QUARTZ = register("white_quartz", Block(FabricBlockSettings.copy(Blocks.QUARTZ_BLOCK).mapColor(DyeColor.WHITE)))
    val WHITE_QUARTZ_STAIRS = register("white_quartz_stairs", StairsBlock(WHITE_QUARTZ.defaultState, FabricBlockSettings.copy(WHITE_QUARTZ).mapColor(DyeColor.WHITE)))
    val WHITE_QUARTZ_SLAB = register("white_quartz_slab", SlabBlock(FabricBlockSettings.copy(WHITE_QUARTZ).mapColor(DyeColor.WHITE)))
    val CHISELED_WHITE_QUARTZ = register("chiseled_white_quartz", Block(FabricBlockSettings.copy(WHITE_QUARTZ).mapColor(DyeColor.WHITE)))
    val WHITE_QUARTZ_BRICKS = register("white_quartz_bricks", Block(FabricBlockSettings.copy(WHITE_QUARTZ).mapColor(DyeColor.WHITE)))
    val WHITE_QUARTZ_PILLAR = register("white_quartz_pillar", PillarBlock(FabricBlockSettings.copy(Blocks.QUARTZ_PILLAR).mapColor(DyeColor.WHITE)))
    val SMOOTH_WHITE_QUARTZ = register("smooth_white_quartz", Block(FabricBlockSettings.copy(Blocks.SMOOTH_QUARTZ).mapColor(DyeColor.WHITE)))
    val SMOOTH_WHITE_QUARTZ_STAIRS = register("smooth_white_quartz_stairs", StairsBlock(SMOOTH_WHITE_QUARTZ.defaultState, FabricBlockSettings.copy(WHITE_QUARTZ).mapColor(DyeColor.WHITE)))
    val SMOOTH_WHITE_QUARTZ_SLAB = register("smooth_white_quartz_slab", SlabBlock(FabricBlockSettings.copy(SMOOTH_WHITE_QUARTZ).mapColor(DyeColor.WHITE)))

    val ORANGE_QUARTZ = register("orange_quartz", Block(FabricBlockSettings.copy(Blocks.QUARTZ_BLOCK).mapColor(DyeColor.ORANGE)))
    val ORANGE_QUARTZ_STAIRS = register("orange_quartz_stairs", StairsBlock(ORANGE_QUARTZ.defaultState, FabricBlockSettings.copy(ORANGE_QUARTZ).mapColor(DyeColor.ORANGE)))
    val ORANGE_QUARTZ_SLAB = register("orange_quartz_slab", SlabBlock(FabricBlockSettings.copy(ORANGE_QUARTZ).mapColor(DyeColor.ORANGE)))
    val CHISELED_ORANGE_QUARTZ = register("chiseled_orange_quartz", Block(FabricBlockSettings.copy(ORANGE_QUARTZ).mapColor(DyeColor.ORANGE)))
    val ORANGE_QUARTZ_BRICKS = register("orange_quartz_bricks", Block(FabricBlockSettings.copy(ORANGE_QUARTZ).mapColor(DyeColor.ORANGE)))
    val ORANGE_QUARTZ_PILLAR = register("orange_quartz_pillar", PillarBlock(FabricBlockSettings.copy(Blocks.QUARTZ_PILLAR).mapColor(DyeColor.ORANGE)))
    val SMOOTH_ORANGE_QUARTZ = register("smooth_orange_quartz", Block(FabricBlockSettings.copy(Blocks.SMOOTH_QUARTZ).mapColor(DyeColor.ORANGE)))
    val SMOOTH_ORANGE_QUARTZ_STAIRS = register("smooth_orange_quartz_stairs", StairsBlock(SMOOTH_ORANGE_QUARTZ.defaultState, FabricBlockSettings.copy(ORANGE_QUARTZ).mapColor(DyeColor.ORANGE)))
    val SMOOTH_ORANGE_QUARTZ_SLAB = register("smooth_orange_quartz_slab", SlabBlock(FabricBlockSettings.copy(SMOOTH_ORANGE_QUARTZ).mapColor(DyeColor.ORANGE)))

    val MAGENTA_QUARTZ = register("magenta_quartz", Block(FabricBlockSettings.copy(Blocks.QUARTZ_BLOCK).mapColor(DyeColor.MAGENTA)))
    val MAGENTA_QUARTZ_STAIRS = register("magenta_quartz_stairs", StairsBlock(MAGENTA_QUARTZ.defaultState, FabricBlockSettings.copy(MAGENTA_QUARTZ).mapColor(DyeColor.MAGENTA)))
    val MAGENTA_QUARTZ_SLAB = register("magenta_quartz_slab", SlabBlock(FabricBlockSettings.copy(MAGENTA_QUARTZ).mapColor(DyeColor.MAGENTA)))
    val CHISELED_MAGENTA_QUARTZ = register("chiseled_magenta_quartz", Block(FabricBlockSettings.copy(MAGENTA_QUARTZ).mapColor(DyeColor.MAGENTA)))
    val MAGENTA_QUARTZ_BRICKS = register("magenta_quartz_bricks", Block(FabricBlockSettings.copy(MAGENTA_QUARTZ).mapColor(DyeColor.MAGENTA)))
    val MAGENTA_QUARTZ_PILLAR = register("magenta_quartz_pillar", PillarBlock(FabricBlockSettings.copy(Blocks.QUARTZ_PILLAR).mapColor(DyeColor.MAGENTA)))
    val SMOOTH_MAGENTA_QUARTZ = register("smooth_magenta_quartz", Block(FabricBlockSettings.copy(Blocks.SMOOTH_QUARTZ).mapColor(DyeColor.MAGENTA)))
    val SMOOTH_MAGENTA_QUARTZ_STAIRS = register("smooth_magenta_quartz_stairs", StairsBlock(SMOOTH_MAGENTA_QUARTZ.defaultState, FabricBlockSettings.copy(MAGENTA_QUARTZ).mapColor(DyeColor.MAGENTA)))
    val SMOOTH_MAGENTA_QUARTZ_SLAB = register("smooth_magenta_quartz_slab", SlabBlock(FabricBlockSettings.copy(SMOOTH_MAGENTA_QUARTZ).mapColor(DyeColor.MAGENTA)))

    val LIGHT_BLUE_QUARTZ = register("light_blue_quartz", Block(FabricBlockSettings.copy(Blocks.QUARTZ_BLOCK).mapColor(DyeColor.LIGHT_BLUE)))
    val LIGHT_BLUE_QUARTZ_STAIRS = register("light_blue_quartz_stairs", StairsBlock(LIGHT_BLUE_QUARTZ.defaultState, FabricBlockSettings.copy(LIGHT_BLUE_QUARTZ).mapColor(DyeColor.LIGHT_BLUE)))
    val LIGHT_BLUE_QUARTZ_SLAB = register("light_blue_quartz_slab", SlabBlock(FabricBlockSettings.copy(LIGHT_BLUE_QUARTZ).mapColor(DyeColor.LIGHT_BLUE)))
    val CHISELED_LIGHT_BLUE_QUARTZ = register("chiseled_light_blue_quartz", Block(FabricBlockSettings.copy(LIGHT_BLUE_QUARTZ).mapColor(DyeColor.LIGHT_BLUE)))
    val LIGHT_BLUE_QUARTZ_BRICKS = register("light_blue_quartz_bricks", Block(FabricBlockSettings.copy(LIGHT_BLUE_QUARTZ).mapColor(DyeColor.LIGHT_BLUE)))
    val LIGHT_BLUE_QUARTZ_PILLAR = register("light_blue_quartz_pillar", PillarBlock(FabricBlockSettings.copy(Blocks.QUARTZ_PILLAR).mapColor(DyeColor.LIGHT_BLUE)))
    val SMOOTH_LIGHT_BLUE_QUARTZ = register("smooth_light_blue_quartz", Block(FabricBlockSettings.copy(Blocks.SMOOTH_QUARTZ).mapColor(DyeColor.LIGHT_BLUE)))
    val SMOOTH_LIGHT_BLUE_QUARTZ_STAIRS = register("smooth_light_blue_quartz_stairs", StairsBlock(SMOOTH_LIGHT_BLUE_QUARTZ.defaultState, FabricBlockSettings.copy(LIGHT_BLUE_QUARTZ).mapColor(DyeColor.LIGHT_BLUE)))
    val SMOOTH_LIGHT_BLUE_QUARTZ_SLAB = register("smooth_light_blue_quartz_slab", SlabBlock(FabricBlockSettings.copy(SMOOTH_LIGHT_BLUE_QUARTZ).mapColor(DyeColor.LIGHT_BLUE)))

    val YELLOW_QUARTZ = register("yellow_quartz", Block(FabricBlockSettings.copy(Blocks.QUARTZ_BLOCK).mapColor(DyeColor.YELLOW)))
    val YELLOW_QUARTZ_STAIRS = register("yellow_quartz_stairs", StairsBlock(YELLOW_QUARTZ.defaultState, FabricBlockSettings.copy(YELLOW_QUARTZ).mapColor(DyeColor.YELLOW)))
    val YELLOW_QUARTZ_SLAB = register("yellow_quartz_slab", SlabBlock(FabricBlockSettings.copy(YELLOW_QUARTZ).mapColor(DyeColor.YELLOW)))
    val CHISELED_YELLOW_QUARTZ = register("chiseled_yellow_quartz", Block(FabricBlockSettings.copy(YELLOW_QUARTZ).mapColor(DyeColor.YELLOW)))
    val YELLOW_QUARTZ_BRICKS = register("yellow_quartz_bricks", Block(FabricBlockSettings.copy(YELLOW_QUARTZ).mapColor(DyeColor.YELLOW)))
    val YELLOW_QUARTZ_PILLAR = register("yellow_quartz_pillar", PillarBlock(FabricBlockSettings.copy(Blocks.QUARTZ_PILLAR).mapColor(DyeColor.YELLOW)))
    val SMOOTH_YELLOW_QUARTZ = register("smooth_yellow_quartz", Block(FabricBlockSettings.copy(Blocks.SMOOTH_QUARTZ).mapColor(DyeColor.YELLOW)))
    val SMOOTH_YELLOW_QUARTZ_STAIRS = register("smooth_yellow_quartz_stairs", StairsBlock(SMOOTH_YELLOW_QUARTZ.defaultState, FabricBlockSettings.copy(YELLOW_QUARTZ).mapColor(DyeColor.YELLOW)))
    val SMOOTH_YELLOW_QUARTZ_SLAB = register("smooth_yellow_quartz_slab", SlabBlock(FabricBlockSettings.copy(SMOOTH_YELLOW_QUARTZ).mapColor(DyeColor.YELLOW)))

    val LIME_QUARTZ = register("lime_quartz", Block(FabricBlockSettings.copy(Blocks.QUARTZ_BLOCK).mapColor(DyeColor.LIME)))
    val LIME_QUARTZ_STAIRS = register("lime_quartz_stairs", StairsBlock(LIME_QUARTZ.defaultState, FabricBlockSettings.copy(LIME_QUARTZ).mapColor(DyeColor.LIME)))
    val LIME_QUARTZ_SLAB = register("lime_quartz_slab", SlabBlock(FabricBlockSettings.copy(LIME_QUARTZ).mapColor(DyeColor.LIME)))
    val CHISELED_LIME_QUARTZ = register("chiseled_lime_quartz", Block(FabricBlockSettings.copy(LIME_QUARTZ).mapColor(DyeColor.LIME)))
    val LIME_QUARTZ_BRICKS = register("lime_quartz_bricks", Block(FabricBlockSettings.copy(LIME_QUARTZ).mapColor(DyeColor.LIME)))
    val LIME_QUARTZ_PILLAR = register("lime_quartz_pillar", PillarBlock(FabricBlockSettings.copy(Blocks.QUARTZ_PILLAR).mapColor(DyeColor.LIME)))
    val SMOOTH_LIME_QUARTZ = register("smooth_lime_quartz", Block(FabricBlockSettings.copy(Blocks.SMOOTH_QUARTZ).mapColor(DyeColor.LIME)))
    val SMOOTH_LIME_QUARTZ_STAIRS = register("smooth_lime_quartz_stairs", StairsBlock(SMOOTH_LIME_QUARTZ.defaultState, FabricBlockSettings.copy(LIME_QUARTZ).mapColor(DyeColor.LIME)))
    val SMOOTH_LIME_QUARTZ_SLAB = register("smooth_lime_quartz_slab", SlabBlock(FabricBlockSettings.copy(SMOOTH_LIME_QUARTZ).mapColor(DyeColor.LIME)))

    val PINK_QUARTZ = register("pink_quartz", Block(FabricBlockSettings.copy(Blocks.QUARTZ_BLOCK).mapColor(DyeColor.PINK)))
    val PINK_QUARTZ_STAIRS = register("pink_quartz_stairs", StairsBlock(PINK_QUARTZ.defaultState, FabricBlockSettings.copy(PINK_QUARTZ).mapColor(DyeColor.PINK)))
    val PINK_QUARTZ_SLAB = register("pink_quartz_slab", SlabBlock(FabricBlockSettings.copy(PINK_QUARTZ).mapColor(DyeColor.PINK)))
    val CHISELED_PINK_QUARTZ = register("chiseled_pink_quartz", Block(FabricBlockSettings.copy(PINK_QUARTZ).mapColor(DyeColor.PINK)))
    val PINK_QUARTZ_BRICKS = register("pink_quartz_bricks", Block(FabricBlockSettings.copy(PINK_QUARTZ).mapColor(DyeColor.PINK)))
    val PINK_QUARTZ_PILLAR = register("pink_quartz_pillar", PillarBlock(FabricBlockSettings.copy(Blocks.QUARTZ_PILLAR).mapColor(DyeColor.PINK)))
    val SMOOTH_PINK_QUARTZ = register("smooth_pink_quartz", Block(FabricBlockSettings.copy(Blocks.SMOOTH_QUARTZ).mapColor(DyeColor.PINK)))
    val SMOOTH_PINK_QUARTZ_STAIRS = register("smooth_pink_quartz_stairs", StairsBlock(SMOOTH_PINK_QUARTZ.defaultState, FabricBlockSettings.copy(PINK_QUARTZ).mapColor(DyeColor.PINK)))
    val SMOOTH_PINK_QUARTZ_SLAB = register("smooth_pink_quartz_slab", SlabBlock(FabricBlockSettings.copy(SMOOTH_PINK_QUARTZ).mapColor(DyeColor.PINK)))

    val GRAY_QUARTZ = register("gray_quartz", Block(FabricBlockSettings.copy(Blocks.QUARTZ_BLOCK).mapColor(DyeColor.GRAY)))
    val GRAY_QUARTZ_STAIRS = register("gray_quartz_stairs", StairsBlock(GRAY_QUARTZ.defaultState, FabricBlockSettings.copy(GRAY_QUARTZ).mapColor(DyeColor.GRAY)))
    val GRAY_QUARTZ_SLAB = register("gray_quartz_slab", SlabBlock(FabricBlockSettings.copy(GRAY_QUARTZ).mapColor(DyeColor.GRAY)))
    val CHISELED_GRAY_QUARTZ = register("chiseled_gray_quartz", Block(FabricBlockSettings.copy(GRAY_QUARTZ).mapColor(DyeColor.GRAY)))
    val GRAY_QUARTZ_BRICKS = register("gray_quartz_bricks", Block(FabricBlockSettings.copy(GRAY_QUARTZ).mapColor(DyeColor.GRAY)))
    val GRAY_QUARTZ_PILLAR = register("gray_quartz_pillar", PillarBlock(FabricBlockSettings.copy(Blocks.QUARTZ_PILLAR).mapColor(DyeColor.GRAY)))
    val SMOOTH_GRAY_QUARTZ = register("smooth_gray_quartz", Block(FabricBlockSettings.copy(Blocks.SMOOTH_QUARTZ).mapColor(DyeColor.GRAY)))
    val SMOOTH_GRAY_QUARTZ_STAIRS = register("smooth_gray_quartz_stairs", StairsBlock(SMOOTH_GRAY_QUARTZ.defaultState, FabricBlockSettings.copy(GRAY_QUARTZ).mapColor(DyeColor.GRAY)))
    val SMOOTH_GRAY_QUARTZ_SLAB = register("smooth_gray_quartz_slab", SlabBlock(FabricBlockSettings.copy(SMOOTH_GRAY_QUARTZ).mapColor(DyeColor.GRAY)))

    val LIGHT_GRAY_QUARTZ = register("light_gray_quartz", Block(FabricBlockSettings.copy(Blocks.QUARTZ_BLOCK).mapColor(DyeColor.LIGHT_GRAY)))
    val LIGHT_GRAY_QUARTZ_STAIRS = register("light_gray_quartz_stairs", StairsBlock(LIGHT_GRAY_QUARTZ.defaultState, FabricBlockSettings.copy(LIGHT_GRAY_QUARTZ).mapColor(DyeColor.LIGHT_GRAY)))
    val LIGHT_GRAY_QUARTZ_SLAB = register("light_gray_quartz_slab", SlabBlock(FabricBlockSettings.copy(LIGHT_GRAY_QUARTZ).mapColor(DyeColor.LIGHT_GRAY)))
    val CHISELED_LIGHT_GRAY_QUARTZ = register("chiseled_light_gray_quartz", Block(FabricBlockSettings.copy(LIGHT_GRAY_QUARTZ).mapColor(DyeColor.LIGHT_GRAY)))
    val LIGHT_GRAY_QUARTZ_BRICKS = register("light_gray_quartz_bricks", Block(FabricBlockSettings.copy(LIGHT_GRAY_QUARTZ).mapColor(DyeColor.LIGHT_GRAY)))
    val LIGHT_GRAY_QUARTZ_PILLAR = register("light_gray_quartz_pillar", PillarBlock(FabricBlockSettings.copy(Blocks.QUARTZ_PILLAR).mapColor(DyeColor.LIGHT_GRAY)))
    val SMOOTH_LIGHT_GRAY_QUARTZ = register("smooth_light_gray_quartz", Block(FabricBlockSettings.copy(Blocks.SMOOTH_QUARTZ).mapColor(DyeColor.LIGHT_GRAY)))
    val SMOOTH_LIGHT_GRAY_QUARTZ_STAIRS = register("smooth_light_gray_quartz_stairs", StairsBlock(SMOOTH_LIGHT_GRAY_QUARTZ.defaultState, FabricBlockSettings.copy(LIGHT_GRAY_QUARTZ).mapColor(DyeColor.LIGHT_GRAY)))
    val SMOOTH_LIGHT_GRAY_QUARTZ_SLAB = register("smooth_light_gray_quartz_slab", SlabBlock(FabricBlockSettings.copy(SMOOTH_LIGHT_GRAY_QUARTZ).mapColor(DyeColor.LIGHT_GRAY)))

    val CYAN_QUARTZ = register("cyan_quartz", Block(FabricBlockSettings.copy(Blocks.QUARTZ_BLOCK).mapColor(DyeColor.CYAN)))
    val CYAN_QUARTZ_STAIRS = register("cyan_quartz_stairs", StairsBlock(CYAN_QUARTZ.defaultState, FabricBlockSettings.copy(CYAN_QUARTZ).mapColor(DyeColor.CYAN)))
    val CYAN_QUARTZ_SLAB = register("cyan_quartz_slab", SlabBlock(FabricBlockSettings.copy(CYAN_QUARTZ).mapColor(DyeColor.CYAN)))
    val CHISELED_CYAN_QUARTZ = register("chiseled_cyan_quartz", Block(FabricBlockSettings.copy(CYAN_QUARTZ).mapColor(DyeColor.CYAN)))
    val CYAN_QUARTZ_BRICKS = register("cyan_quartz_bricks", Block(FabricBlockSettings.copy(CYAN_QUARTZ).mapColor(DyeColor.CYAN)))
    val CYAN_QUARTZ_PILLAR = register("cyan_quartz_pillar", PillarBlock(FabricBlockSettings.copy(Blocks.QUARTZ_PILLAR).mapColor(DyeColor.CYAN)))
    val SMOOTH_CYAN_QUARTZ = register("smooth_cyan_quartz", Block(FabricBlockSettings.copy(Blocks.SMOOTH_QUARTZ).mapColor(DyeColor.CYAN)))
    val SMOOTH_CYAN_QUARTZ_STAIRS = register("smooth_cyan_quartz_stairs", StairsBlock(SMOOTH_CYAN_QUARTZ.defaultState, FabricBlockSettings.copy(CYAN_QUARTZ).mapColor(DyeColor.CYAN)))
    val SMOOTH_CYAN_QUARTZ_SLAB = register("smooth_cyan_quartz_slab", SlabBlock(FabricBlockSettings.copy(SMOOTH_CYAN_QUARTZ).mapColor(DyeColor.CYAN)))

    val PURPLE_QUARTZ = register("purple_quartz", Block(FabricBlockSettings.copy(Blocks.QUARTZ_BLOCK).mapColor(DyeColor.PURPLE)))
    val PURPLE_QUARTZ_STAIRS = register("purple_quartz_stairs", StairsBlock(PURPLE_QUARTZ.defaultState, FabricBlockSettings.copy(PURPLE_QUARTZ).mapColor(DyeColor.PURPLE)))
    val PURPLE_QUARTZ_SLAB = register("purple_quartz_slab", SlabBlock(FabricBlockSettings.copy(PURPLE_QUARTZ).mapColor(DyeColor.PURPLE)))
    val CHISELED_PURPLE_QUARTZ = register("chiseled_purple_quartz", Block(FabricBlockSettings.copy(PURPLE_QUARTZ).mapColor(DyeColor.PURPLE)))
    val PURPLE_QUARTZ_BRICKS = register("purple_quartz_bricks", Block(FabricBlockSettings.copy(PURPLE_QUARTZ).mapColor(DyeColor.PURPLE)))
    val PURPLE_QUARTZ_PILLAR = register("purple_quartz_pillar", PillarBlock(FabricBlockSettings.copy(Blocks.QUARTZ_PILLAR).mapColor(DyeColor.PURPLE)))
    val SMOOTH_PURPLE_QUARTZ = register("smooth_purple_quartz", Block(FabricBlockSettings.copy(Blocks.SMOOTH_QUARTZ).mapColor(DyeColor.PURPLE)))
    val SMOOTH_PURPLE_QUARTZ_STAIRS = register("smooth_purple_quartz_stairs", StairsBlock(SMOOTH_PURPLE_QUARTZ.defaultState, FabricBlockSettings.copy(PURPLE_QUARTZ).mapColor(DyeColor.PURPLE)))
    val SMOOTH_PURPLE_QUARTZ_SLAB = register("smooth_purple_quartz_slab", SlabBlock(FabricBlockSettings.copy(SMOOTH_PURPLE_QUARTZ).mapColor(DyeColor.PURPLE)))

    val BLUE_QUARTZ = register("blue_quartz", Block(FabricBlockSettings.copy(Blocks.QUARTZ_BLOCK).mapColor(DyeColor.BLUE)))
    val BLUE_QUARTZ_STAIRS = register("blue_quartz_stairs", StairsBlock(BLUE_QUARTZ.defaultState, FabricBlockSettings.copy(BLUE_QUARTZ).mapColor(DyeColor.BLUE)))
    val BLUE_QUARTZ_SLAB = register("blue_quartz_slab", SlabBlock(FabricBlockSettings.copy(BLUE_QUARTZ).mapColor(DyeColor.BLUE)))
    val CHISELED_BLUE_QUARTZ = register("chiseled_blue_quartz", Block(FabricBlockSettings.copy(BLUE_QUARTZ).mapColor(DyeColor.BLUE)))
    val BLUE_QUARTZ_BRICKS = register("blue_quartz_bricks", Block(FabricBlockSettings.copy(BLUE_QUARTZ).mapColor(DyeColor.BLUE)))
    val BLUE_QUARTZ_PILLAR = register("blue_quartz_pillar", PillarBlock(FabricBlockSettings.copy(Blocks.QUARTZ_PILLAR).mapColor(DyeColor.BLUE)))
    val SMOOTH_BLUE_QUARTZ = register("smooth_blue_quartz", Block(FabricBlockSettings.copy(Blocks.SMOOTH_QUARTZ).mapColor(DyeColor.BLUE)))
    val SMOOTH_BLUE_QUARTZ_STAIRS = register("smooth_blue_quartz_stairs", StairsBlock(SMOOTH_BLUE_QUARTZ.defaultState, FabricBlockSettings.copy(BLUE_QUARTZ).mapColor(DyeColor.BLUE)))
    val SMOOTH_BLUE_QUARTZ_SLAB = register("smooth_blue_quartz_slab", SlabBlock(FabricBlockSettings.copy(SMOOTH_BLUE_QUARTZ).mapColor(DyeColor.BLUE)))

    val BROWN_QUARTZ = register("brown_quartz", Block(FabricBlockSettings.copy(Blocks.QUARTZ_BLOCK).mapColor(DyeColor.BROWN)))
    val BROWN_QUARTZ_STAIRS = register("brown_quartz_stairs", StairsBlock(BROWN_QUARTZ.defaultState, FabricBlockSettings.copy(BROWN_QUARTZ).mapColor(DyeColor.BROWN)))
    val BROWN_QUARTZ_SLAB = register("brown_quartz_slab", SlabBlock(FabricBlockSettings.copy(BROWN_QUARTZ).mapColor(DyeColor.BROWN)))
    val CHISELED_BROWN_QUARTZ = register("chiseled_brown_quartz", Block(FabricBlockSettings.copy(BROWN_QUARTZ).mapColor(DyeColor.BROWN)))
    val BROWN_QUARTZ_BRICKS = register("brown_quartz_bricks", Block(FabricBlockSettings.copy(BROWN_QUARTZ).mapColor(DyeColor.BROWN)))
    val BROWN_QUARTZ_PILLAR = register("brown_quartz_pillar", PillarBlock(FabricBlockSettings.copy(Blocks.QUARTZ_PILLAR).mapColor(DyeColor.BROWN)))
    val SMOOTH_BROWN_QUARTZ = register("smooth_brown_quartz", Block(FabricBlockSettings.copy(Blocks.SMOOTH_QUARTZ).mapColor(DyeColor.BROWN)))
    val SMOOTH_BROWN_QUARTZ_STAIRS = register("smooth_brown_quartz_stairs", StairsBlock(SMOOTH_BROWN_QUARTZ.defaultState, FabricBlockSettings.copy(BROWN_QUARTZ).mapColor(DyeColor.BROWN)))
    val SMOOTH_BROWN_QUARTZ_SLAB = register("smooth_brown_quartz_slab", SlabBlock(FabricBlockSettings.copy(SMOOTH_BROWN_QUARTZ).mapColor(DyeColor.BROWN)))

    val GREEN_QUARTZ = register("green_quartz", Block(FabricBlockSettings.copy(Blocks.QUARTZ_BLOCK).mapColor(DyeColor.GREEN)))
    val GREEN_QUARTZ_STAIRS = register("green_quartz_stairs", StairsBlock(GREEN_QUARTZ.defaultState, FabricBlockSettings.copy(GREEN_QUARTZ).mapColor(DyeColor.GREEN)))
    val GREEN_QUARTZ_SLAB = register("green_quartz_slab", SlabBlock(FabricBlockSettings.copy(GREEN_QUARTZ).mapColor(DyeColor.GREEN)))
    val CHISELED_GREEN_QUARTZ = register("chiseled_green_quartz", Block(FabricBlockSettings.copy(GREEN_QUARTZ).mapColor(DyeColor.GREEN)))
    val GREEN_QUARTZ_BRICKS = register("green_quartz_bricks", Block(FabricBlockSettings.copy(GREEN_QUARTZ).mapColor(DyeColor.GREEN)))
    val GREEN_QUARTZ_PILLAR = register("green_quartz_pillar", PillarBlock(FabricBlockSettings.copy(Blocks.QUARTZ_PILLAR).mapColor(DyeColor.GREEN)))
    val SMOOTH_GREEN_QUARTZ = register("smooth_green_quartz", Block(FabricBlockSettings.copy(Blocks.SMOOTH_QUARTZ).mapColor(DyeColor.GREEN)))
    val SMOOTH_GREEN_QUARTZ_STAIRS = register("smooth_green_quartz_stairs", StairsBlock(SMOOTH_GREEN_QUARTZ.defaultState, FabricBlockSettings.copy(GREEN_QUARTZ).mapColor(DyeColor.GREEN)))
    val SMOOTH_GREEN_QUARTZ_SLAB = register("smooth_green_quartz_slab", SlabBlock(FabricBlockSettings.copy(SMOOTH_GREEN_QUARTZ).mapColor(DyeColor.GREEN)))

    val RED_QUARTZ = register("red_quartz", Block(FabricBlockSettings.copy(Blocks.QUARTZ_BLOCK).mapColor(DyeColor.RED)))
    val RED_QUARTZ_STAIRS = register("red_quartz_stairs", StairsBlock(RED_QUARTZ.defaultState, FabricBlockSettings.copy(RED_QUARTZ).mapColor(DyeColor.RED)))
    val RED_QUARTZ_SLAB = register("red_quartz_slab", SlabBlock(FabricBlockSettings.copy(RED_QUARTZ).mapColor(DyeColor.RED)))
    val CHISELED_RED_QUARTZ = register("chiseled_red_quartz", Block(FabricBlockSettings.copy(RED_QUARTZ).mapColor(DyeColor.RED)))
    val RED_QUARTZ_BRICKS = register("red_quartz_bricks", Block(FabricBlockSettings.copy(RED_QUARTZ).mapColor(DyeColor.RED)))
    val RED_QUARTZ_PILLAR = register("red_quartz_pillar", PillarBlock(FabricBlockSettings.copy(Blocks.QUARTZ_PILLAR).mapColor(DyeColor.RED)))
    val SMOOTH_RED_QUARTZ = register("smooth_red_quartz", Block(FabricBlockSettings.copy(Blocks.SMOOTH_QUARTZ).mapColor(DyeColor.RED)))
    val SMOOTH_RED_QUARTZ_STAIRS = register("smooth_red_quartz_stairs", StairsBlock(SMOOTH_RED_QUARTZ.defaultState, FabricBlockSettings.copy(RED_QUARTZ).mapColor(DyeColor.RED)))
    val SMOOTH_RED_QUARTZ_SLAB = register("smooth_red_quartz_slab", SlabBlock(FabricBlockSettings.copy(SMOOTH_RED_QUARTZ).mapColor(DyeColor.RED)))

    val BLACK_QUARTZ = register("black_quartz", Block(FabricBlockSettings.copy(Blocks.QUARTZ_BLOCK).mapColor(DyeColor.BLACK)))
    val BLACK_QUARTZ_STAIRS = register("black_quartz_stairs", StairsBlock(BLACK_QUARTZ.defaultState, FabricBlockSettings.copy(BLACK_QUARTZ).mapColor(DyeColor.BLACK)))
    val BLACK_QUARTZ_SLAB = register("black_quartz_slab", SlabBlock(FabricBlockSettings.copy(BLACK_QUARTZ).mapColor(DyeColor.BLACK)))
    val CHISELED_BLACK_QUARTZ = register("chiseled_black_quartz", Block(FabricBlockSettings.copy(BLACK_QUARTZ).mapColor(DyeColor.BLACK)))
    val BLACK_QUARTZ_BRICKS = register("black_quartz_bricks", Block(FabricBlockSettings.copy(BLACK_QUARTZ).mapColor(DyeColor.BLACK)))
    val BLACK_QUARTZ_PILLAR = register("black_quartz_pillar", PillarBlock(FabricBlockSettings.copy(Blocks.QUARTZ_PILLAR).mapColor(DyeColor.BLACK)))
    val SMOOTH_BLACK_QUARTZ = register("smooth_black_quartz", Block(FabricBlockSettings.copy(Blocks.SMOOTH_QUARTZ).mapColor(DyeColor.BLACK)))
    val SMOOTH_BLACK_QUARTZ_STAIRS = register("smooth_black_quartz_stairs", StairsBlock(SMOOTH_BLACK_QUARTZ.defaultState, FabricBlockSettings.copy(BLACK_QUARTZ).mapColor(DyeColor.BLACK)))
    val SMOOTH_BLACK_QUARTZ_SLAB = register("smooth_black_quartz_slab", SlabBlock(FabricBlockSettings.copy(SMOOTH_BLACK_QUARTZ).mapColor(DyeColor.BLACK)))

    // endregion

    // region Bricks

    val CRACKED_BRICKS = register("cracked_bricks", Block(FabricBlockSettings.copy(Blocks.BRICKS)))
    val CRACKED_BRICK_STAIRS = register("cracked_brick_stairs", StairsBlock(CRACKED_BRICKS.defaultState, FabricBlockSettings.copy(CRACKED_BRICKS).mapColor(DyeColor.WHITE)))
    val CRACKED_BRICK_SLAB = register("cracked_brick_slab", SlabBlock(FabricBlockSettings.copy(CRACKED_BRICKS).mapColor(DyeColor.WHITE)))
    val CRACKED_BRICK_WALL = register("cracked_brick_wall", WallBlock(FabricBlockSettings.copy(Blocks.BRICK_WALL).mapColor(DyeColor.WHITE)))

    val WHITE_BRICKS = register("white_bricks", Block(FabricBlockSettings.copy(Blocks.BRICKS).mapColor(DyeColor.WHITE)))
    val CRACKED_WHITE_BRICKS = register("cracked_white_bricks", Block(FabricBlockSettings.copy(WHITE_BRICKS)))
    val WHITE_BRICK_STAIRS = register("white_brick_stairs", StairsBlock(WHITE_BRICKS.defaultState, FabricBlockSettings.copy(WHITE_BRICKS).mapColor(DyeColor.WHITE)))
    val WHITE_BRICK_SLAB = register("white_brick_slab", SlabBlock(FabricBlockSettings.copy(WHITE_BRICKS).mapColor(DyeColor.WHITE)))
    val WHITE_BRICK_WALL = register("white_brick_wall", WallBlock(FabricBlockSettings.copy(Blocks.BRICK_WALL).mapColor(DyeColor.WHITE)))

    val ORANGE_BRICKS = register("orange_bricks", Block(FabricBlockSettings.copy(Blocks.BRICKS).mapColor(DyeColor.ORANGE)))
    val CRACKED_ORANGE_BRICKS = register("cracked_orange_bricks", Block(FabricBlockSettings.copy(ORANGE_BRICKS)))
    val ORANGE_BRICK_STAIRS = register("orange_brick_stairs", StairsBlock(ORANGE_BRICKS.defaultState, FabricBlockSettings.copy(ORANGE_BRICKS).mapColor(DyeColor.ORANGE)))
    val ORANGE_BRICK_SLAB = register("orange_brick_slab", SlabBlock(FabricBlockSettings.copy(ORANGE_BRICKS).mapColor(DyeColor.ORANGE)))
    val ORANGE_BRICK_WALL = register("orange_brick_wall", WallBlock(FabricBlockSettings.copy(Blocks.BRICK_WALL).mapColor(DyeColor.ORANGE)))

    val MAGENTA_BRICKS = register("magenta_bricks", Block(FabricBlockSettings.copy(Blocks.BRICKS).mapColor(DyeColor.MAGENTA)))
    val CRACKED_MAGENTA_BRICKS = register("cracked_magenta_bricks", Block(FabricBlockSettings.copy(MAGENTA_BRICKS)))
    val MAGENTA_BRICK_STAIRS = register("magenta_brick_stairs", StairsBlock(MAGENTA_BRICKS.defaultState, FabricBlockSettings.copy(MAGENTA_BRICKS).mapColor(DyeColor.MAGENTA)))
    val MAGENTA_BRICK_SLAB = register("magenta_brick_slab", SlabBlock(FabricBlockSettings.copy(MAGENTA_BRICKS).mapColor(DyeColor.MAGENTA)))
    val MAGENTA_BRICK_WALL = register("magenta_brick_wall", WallBlock(FabricBlockSettings.copy(Blocks.BRICK_WALL).mapColor(DyeColor.MAGENTA)))

    val LIGHT_BLUE_BRICKS = register("light_blue_bricks", Block(FabricBlockSettings.copy(Blocks.BRICKS).mapColor(DyeColor.LIGHT_BLUE)))
    val CRACKED_LIGHT_BLUE_BRICKS = register("cracked_light_blue_bricks", Block(FabricBlockSettings.copy(LIGHT_BLUE_BRICKS)))
    val LIGHT_BLUE_BRICK_STAIRS = register("light_blue_brick_stairs", StairsBlock(LIGHT_BLUE_BRICKS.defaultState, FabricBlockSettings.copy(LIGHT_BLUE_BRICKS).mapColor(DyeColor.LIGHT_BLUE)))
    val LIGHT_BLUE_BRICK_SLAB = register("light_blue_brick_slab", SlabBlock(FabricBlockSettings.copy(LIGHT_BLUE_BRICKS).mapColor(DyeColor.LIGHT_BLUE)))
    val LIGHT_BLUE_BRICK_WALL = register("light_blue_brick_wall", WallBlock(FabricBlockSettings.copy(Blocks.BRICK_WALL).mapColor(DyeColor.LIGHT_BLUE)))

    val YELLOW_BRICKS = register("yellow_bricks", Block(FabricBlockSettings.copy(Blocks.BRICKS).mapColor(DyeColor.YELLOW)))
    val CRACKED_YELLOW_BRICKS = register("cracked_yellow_bricks", Block(FabricBlockSettings.copy(YELLOW_BRICKS)))
    val YELLOW_BRICK_STAIRS = register("yellow_brick_stairs", StairsBlock(YELLOW_BRICKS.defaultState, FabricBlockSettings.copy(YELLOW_BRICKS).mapColor(DyeColor.YELLOW)))
    val YELLOW_BRICK_SLAB = register("yellow_brick_slab", SlabBlock(FabricBlockSettings.copy(YELLOW_BRICKS).mapColor(DyeColor.YELLOW)))
    val YELLOW_BRICK_WALL = register("yellow_brick_wall", WallBlock(FabricBlockSettings.copy(Blocks.BRICK_WALL).mapColor(DyeColor.YELLOW)))

    val LIME_BRICKS = register("lime_bricks", Block(FabricBlockSettings.copy(Blocks.BRICKS).mapColor(DyeColor.LIME)))
    val CRACKED_LIME_BRICKS = register("cracked_lime_bricks", Block(FabricBlockSettings.copy(LIME_BRICKS)))
    val LIME_BRICK_STAIRS = register("lime_brick_stairs", StairsBlock(LIME_BRICKS.defaultState, FabricBlockSettings.copy(LIME_BRICKS).mapColor(DyeColor.LIME)))
    val LIME_BRICK_SLAB = register("lime_brick_slab", SlabBlock(FabricBlockSettings.copy(LIME_BRICKS).mapColor(DyeColor.LIME)))
    val LIME_BRICK_WALL = register("lime_brick_wall", WallBlock(FabricBlockSettings.copy(Blocks.BRICK_WALL).mapColor(DyeColor.LIME)))

    val PINK_BRICKS = register("pink_bricks", Block(FabricBlockSettings.copy(Blocks.BRICKS).mapColor(DyeColor.PINK)))
    val CRACKED_PINK_BRICKS = register("cracked_pink_bricks", Block(FabricBlockSettings.copy(PINK_BRICKS)))
    val PINK_BRICK_STAIRS = register("pink_brick_stairs", StairsBlock(PINK_BRICKS.defaultState, FabricBlockSettings.copy(PINK_BRICKS).mapColor(DyeColor.PINK)))
    val PINK_BRICK_SLAB = register("pink_brick_slab", SlabBlock(FabricBlockSettings.copy(PINK_BRICKS).mapColor(DyeColor.PINK)))
    val PINK_BRICK_WALL = register("pink_brick_wall", WallBlock(FabricBlockSettings.copy(Blocks.BRICK_WALL).mapColor(DyeColor.PINK)))

    val GRAY_BRICKS = register("gray_bricks", Block(FabricBlockSettings.copy(Blocks.BRICKS).mapColor(DyeColor.GRAY)))
    val CRACKED_GRAY_BRICKS = register("cracked_gray_bricks", Block(FabricBlockSettings.copy(GRAY_BRICKS)))
    val GRAY_BRICK_STAIRS = register("gray_brick_stairs", StairsBlock(GRAY_BRICKS.defaultState, FabricBlockSettings.copy(GRAY_BRICKS).mapColor(DyeColor.GRAY)))
    val GRAY_BRICK_SLAB = register("gray_brick_slab", SlabBlock(FabricBlockSettings.copy(GRAY_BRICKS).mapColor(DyeColor.GRAY)))
    val GRAY_BRICK_WALL = register("gray_brick_wall", WallBlock(FabricBlockSettings.copy(Blocks.BRICK_WALL).mapColor(DyeColor.GRAY)))

    val LIGHT_GRAY_BRICKS = register("light_gray_bricks", Block(FabricBlockSettings.copy(Blocks.BRICKS).mapColor(DyeColor.LIGHT_GRAY)))
    val CRACKED_LIGHT_GRAY_BRICKS = register("cracked_light_gray_bricks", Block(FabricBlockSettings.copy(LIGHT_GRAY_BRICKS)))
    val LIGHT_GRAY_BRICK_STAIRS = register("light_gray_brick_stairs", StairsBlock(LIGHT_GRAY_BRICKS.defaultState, FabricBlockSettings.copy(LIGHT_GRAY_BRICKS).mapColor(DyeColor.LIGHT_GRAY)))
    val LIGHT_GRAY_BRICK_SLAB = register("light_gray_brick_slab", SlabBlock(FabricBlockSettings.copy(LIGHT_GRAY_BRICKS).mapColor(DyeColor.LIGHT_GRAY)))
    val LIGHT_GRAY_BRICK_WALL = register("light_gray_brick_wall", WallBlock(FabricBlockSettings.copy(Blocks.BRICK_WALL).mapColor(DyeColor.LIGHT_GRAY)))

    val CYAN_BRICKS = register("cyan_bricks", Block(FabricBlockSettings.copy(Blocks.BRICKS).mapColor(DyeColor.CYAN)))
    val CRACKED_CYAN_BRICKS = register("cracked_cyan_bricks", Block(FabricBlockSettings.copy(CYAN_BRICKS)))
    val CYAN_BRICK_STAIRS = register("cyan_brick_stairs", StairsBlock(CYAN_BRICKS.defaultState, FabricBlockSettings.copy(CYAN_BRICKS).mapColor(DyeColor.CYAN)))
    val CYAN_BRICK_SLAB = register("cyan_brick_slab", SlabBlock(FabricBlockSettings.copy(CYAN_BRICKS).mapColor(DyeColor.CYAN)))
    val CYAN_BRICK_WALL = register("cyan_brick_wall", WallBlock(FabricBlockSettings.copy(Blocks.BRICK_WALL).mapColor(DyeColor.CYAN)))

    val PURPLE_BRICKS = register("purple_bricks", Block(FabricBlockSettings.copy(Blocks.BRICKS).mapColor(DyeColor.PURPLE)))
    val CRACKED_PURPLE_BRICKS = register("cracked_purple_bricks", Block(FabricBlockSettings.copy(PURPLE_BRICKS)))
    val PURPLE_BRICK_STAIRS = register("purple_brick_stairs", StairsBlock(PURPLE_BRICKS.defaultState, FabricBlockSettings.copy(PURPLE_BRICKS).mapColor(DyeColor.PURPLE)))
    val PURPLE_BRICK_SLAB = register("purple_brick_slab", SlabBlock(FabricBlockSettings.copy(PURPLE_BRICKS).mapColor(DyeColor.PURPLE)))
    val PURPLE_BRICK_WALL = register("purple_brick_wall", WallBlock(FabricBlockSettings.copy(Blocks.BRICK_WALL).mapColor(DyeColor.PURPLE)))

    val BLUE_BRICKS = register("blue_bricks", Block(FabricBlockSettings.copy(Blocks.BRICKS).mapColor(DyeColor.BLUE)))
    val CRACKED_BLUE_BRICKS = register("cracked_blue_bricks", Block(FabricBlockSettings.copy(BLUE_BRICKS)))
    val BLUE_BRICK_STAIRS = register("blue_brick_stairs", StairsBlock(BLUE_BRICKS.defaultState, FabricBlockSettings.copy(BLUE_BRICKS).mapColor(DyeColor.BLUE)))
    val BLUE_BRICK_SLAB = register("blue_brick_slab", SlabBlock(FabricBlockSettings.copy(BLUE_BRICKS).mapColor(DyeColor.BLUE)))
    val BLUE_BRICK_WALL = register("blue_brick_wall", WallBlock(FabricBlockSettings.copy(Blocks.BRICK_WALL).mapColor(DyeColor.BLUE)))

    val BROWN_BRICKS = register("brown_bricks", Block(FabricBlockSettings.copy(Blocks.BRICKS).mapColor(DyeColor.BROWN)))
    val CRACKED_BROWN_BRICKS = register("cracked_brown_bricks", Block(FabricBlockSettings.copy(BROWN_BRICKS)))
    val BROWN_BRICK_STAIRS = register("cracked_brown_brick_stairs", StairsBlock(BROWN_BRICKS.defaultState, FabricBlockSettings.copy(BROWN_BRICKS).mapColor(DyeColor.BROWN)))
    val BROWN_BRICK_SLAB = register("brown_brick_slab", SlabBlock(FabricBlockSettings.copy(BROWN_BRICKS).mapColor(DyeColor.BROWN)))
    val BROWN_BRICK_WALL = register("brown_brick_wall", WallBlock(FabricBlockSettings.copy(Blocks.BRICK_WALL).mapColor(DyeColor.BROWN)))

    val GREEN_BRICKS = register("green_bricks", Block(FabricBlockSettings.copy(Blocks.BRICKS).mapColor(DyeColor.GREEN)))
    val CRACKED_GREEN_BRICKS = register("cracked_green_bricks", Block(FabricBlockSettings.copy(GREEN_BRICKS)))
    val GREEN_BRICK_STAIRS = register("green_brick_stairs", StairsBlock(GREEN_BRICKS.defaultState, FabricBlockSettings.copy(GREEN_BRICKS).mapColor(DyeColor.GREEN)))
    val GREEN_BRICK_SLAB = register("green_brick_slab", SlabBlock(FabricBlockSettings.copy(GREEN_BRICKS).mapColor(DyeColor.GREEN)))
    val GREEN_BRICK_WALL = register("green_brick_wall", WallBlock(FabricBlockSettings.copy(Blocks.BRICK_WALL).mapColor(DyeColor.GREEN)))

    val RED_BRICKS = register("red_bricks", Block(FabricBlockSettings.copy(Blocks.BRICKS).mapColor(DyeColor.RED)))
    val CRACKED_RED_BRICKS = register("cracked_red_bricks", Block(FabricBlockSettings.copy(RED_BRICKS)))
    val RED_BRICK_STAIRS = register("red_brick_stairs", StairsBlock(RED_BRICKS.defaultState, FabricBlockSettings.copy(RED_BRICKS).mapColor(DyeColor.RED)))
    val RED_BRICK_SLAB = register("red_brick_slab", SlabBlock(FabricBlockSettings.copy(RED_BRICKS).mapColor(DyeColor.RED)))
    val RED_BRICK_WALL = register("red_brick_wall", WallBlock(FabricBlockSettings.copy(Blocks.BRICK_WALL).mapColor(DyeColor.RED)))

    val BLACK_BRICKS = register("black_bricks", Block(FabricBlockSettings.copy(Blocks.BRICKS).mapColor(DyeColor.BLACK)))
    val CRACKED_BLACK_BRICKS = register("cracked_black_bricks", Block(FabricBlockSettings.copy(BLACK_BRICKS)))
    val BLACK_BRICK_STAIRS = register("black_brick_stairs", StairsBlock(BLACK_BRICKS.defaultState, FabricBlockSettings.copy(BLACK_BRICKS).mapColor(DyeColor.BLACK)))
    val BLACK_BRICK_SLAB = register("black_brick_slab", SlabBlock(FabricBlockSettings.copy(BLACK_BRICKS).mapColor(DyeColor.BLACK)))
    val BLACK_BRICK_WALL = register("black_brick_wall", WallBlock(FabricBlockSettings.copy(Blocks.BRICK_WALL).mapColor(DyeColor.BLACK)))

    val MOSSY_BRICKS = register("mossy_bricks", Block(FabricBlockSettings.copy(Blocks.BRICKS).mapColor(DyeColor.BLACK)))
    val MOSSY_BRICK_STAIRS = register("mossy_brick_stairs", StairsBlock(Blocks.BRICKS.defaultState, FabricBlockSettings.copy(Blocks.BRICKS).mapColor(DyeColor.BLACK)))
    val MOSSY_BRICK_SLAB = register("mossy_brick_slab", SlabBlock(FabricBlockSettings.copy(Blocks.BRICKS).mapColor(DyeColor.BLACK)))
    val MOSSY_BRICK_WALL = register("mossy_brick_wall", WallBlock(FabricBlockSettings.copy(Blocks.BRICK_WALL).mapColor(DyeColor.BLACK)))

    val MOSSY_WHITE_BRICKS = register("mossy_white_bricks", Block(FabricBlockSettings.copy(Blocks.BRICKS).mapColor(DyeColor.WHITE)))
    val MOSSY_WHITE_BRICK_STAIRS = register("mossy_white_brick_stairs", StairsBlock(WHITE_BRICKS.defaultState, FabricBlockSettings.copy(MOSSY_WHITE_BRICKS).mapColor(DyeColor.WHITE)))
    val MOSSY_WHITE_BRICK_SLAB = register("mossy_white_brick_slab", SlabBlock(FabricBlockSettings.copy(MOSSY_WHITE_BRICKS).mapColor(DyeColor.WHITE)))
    val MOSSY_WHITE_BRICK_WALL = register("mossy_white_brick_wall", WallBlock(FabricBlockSettings.copy(Blocks.BRICK_WALL).mapColor(DyeColor.WHITE)))

    val MOSSY_ORANGE_BRICKS = register("mossy_orange_bricks", Block(FabricBlockSettings.copy(Blocks.BRICKS).mapColor(DyeColor.ORANGE)))
    val MOSSY_ORANGE_BRICK_STAIRS = register("mossy_orange_brick_stairs", StairsBlock(MOSSY_ORANGE_BRICKS.defaultState, FabricBlockSettings.copy(MOSSY_ORANGE_BRICKS).mapColor(DyeColor.ORANGE)))
    val MOSSY_ORANGE_BRICK_SLAB = register("mossy_orange_brick_slab", SlabBlock(FabricBlockSettings.copy(MOSSY_ORANGE_BRICKS).mapColor(DyeColor.ORANGE)))
    val MOSSY_ORANGE_BRICK_WALL = register("mossy_orange_brick_wall", WallBlock(FabricBlockSettings.copy(Blocks.BRICK_WALL).mapColor(DyeColor.ORANGE)))

    val MOSSY_MAGENTA_BRICKS = register("mossy_magenta_bricks", Block(FabricBlockSettings.copy(Blocks.BRICKS).mapColor(DyeColor.MAGENTA)))
    val MOSSY_MAGENTA_BRICK_STAIRS = register("mossy_magenta_brick_stairs", StairsBlock(MOSSY_MAGENTA_BRICKS.defaultState, FabricBlockSettings.copy(MOSSY_MAGENTA_BRICKS).mapColor(DyeColor.MAGENTA)))
    val MOSSY_MAGENTA_BRICK_SLAB = register("mossy_magenta_brick_slab", SlabBlock(FabricBlockSettings.copy(MOSSY_MAGENTA_BRICKS).mapColor(DyeColor.MAGENTA)))
    val MOSSY_MAGENTA_BRICK_WALL = register("mossy_magenta_brick_wall", WallBlock(FabricBlockSettings.copy(Blocks.BRICK_WALL).mapColor(DyeColor.MAGENTA)))

    val MOSSY_LIGHT_BLUE_BRICKS = register("mossy_light_blue_bricks", Block(FabricBlockSettings.copy(Blocks.BRICKS).mapColor(DyeColor.LIGHT_BLUE)))
    val MOSSY_LIGHT_BLUE_BRICK_STAIRS = register("mossy_light_blue_brick_stairs", StairsBlock(MOSSY_LIGHT_BLUE_BRICKS.defaultState, FabricBlockSettings.copy(MOSSY_LIGHT_BLUE_BRICKS).mapColor(DyeColor.LIGHT_BLUE)))
    val MOSSY_LIGHT_BLUE_BRICK_SLAB = register("mossy_light_blue_brick_slab", SlabBlock(FabricBlockSettings.copy(MOSSY_LIGHT_BLUE_BRICKS).mapColor(DyeColor.LIGHT_BLUE)))
    val MOSSY_LIGHT_BLUE_BRICK_WALL = register("mossy_light_blue_brick_wall", WallBlock(FabricBlockSettings.copy(Blocks.BRICK_WALL).mapColor(DyeColor.LIGHT_BLUE)))

    val MOSSY_YELLOW_BRICKS = register("mossy_yellow_bricks", Block(FabricBlockSettings.copy(Blocks.BRICKS).mapColor(DyeColor.YELLOW)))
    val MOSSY_YELLOW_BRICK_STAIRS = register("mossy_yellow_brick_stairs", StairsBlock(MOSSY_YELLOW_BRICKS.defaultState, FabricBlockSettings.copy(MOSSY_YELLOW_BRICKS).mapColor(DyeColor.YELLOW)))
    val MOSSY_YELLOW_BRICK_SLAB = register("mossy_yellow_brick_slab", SlabBlock(FabricBlockSettings.copy(MOSSY_YELLOW_BRICKS).mapColor(DyeColor.YELLOW)))
    val MOSSY_YELLOW_BRICK_WALL = register("mossy_yellow_brick_wall", WallBlock(FabricBlockSettings.copy(Blocks.BRICK_WALL).mapColor(DyeColor.YELLOW)))

    val MOSSY_LIME_BRICKS = register("mossy_lime_bricks", Block(FabricBlockSettings.copy(Blocks.BRICKS).mapColor(DyeColor.LIME)))
    val MOSSY_LIME_BRICK_STAIRS = register("mossy_lime_brick_stairs", StairsBlock(MOSSY_LIME_BRICKS.defaultState, FabricBlockSettings.copy(MOSSY_LIME_BRICKS).mapColor(DyeColor.LIME)))
    val MOSSY_LIME_BRICK_SLAB = register("mossy_lime_brick_slab", SlabBlock(FabricBlockSettings.copy(MOSSY_LIME_BRICKS).mapColor(DyeColor.LIME)))
    val MOSSY_LIME_BRICK_WALL = register("mossy_lime_brick_wall", WallBlock(FabricBlockSettings.copy(Blocks.BRICK_WALL).mapColor(DyeColor.LIME)))

    val MOSSY_PINK_BRICKS = register("mossy_pink_bricks", Block(FabricBlockSettings.copy(Blocks.BRICKS).mapColor(DyeColor.PINK)))
    val MOSSY_PINK_BRICK_STAIRS = register("mossy_pink_brick_stairs", StairsBlock(MOSSY_PINK_BRICKS.defaultState, FabricBlockSettings.copy(MOSSY_PINK_BRICKS).mapColor(DyeColor.PINK)))
    val MOSSY_PINK_BRICK_SLAB = register("mossy_pink_brick_slab", SlabBlock(FabricBlockSettings.copy(MOSSY_PINK_BRICKS).mapColor(DyeColor.PINK)))
    val MOSSY_PINK_BRICK_WALL = register("mossy_pink_brick_wall", WallBlock(FabricBlockSettings.copy(Blocks.BRICK_WALL).mapColor(DyeColor.PINK)))

    val MOSSY_GRAY_BRICKS = register("mossy_gray_bricks", Block(FabricBlockSettings.copy(Blocks.BRICKS).mapColor(DyeColor.GRAY)))
    val MOSSY_GRAY_BRICK_STAIRS = register("mossy_gray_brick_stairs", StairsBlock(MOSSY_GRAY_BRICKS.defaultState, FabricBlockSettings.copy(MOSSY_GRAY_BRICKS).mapColor(DyeColor.GRAY)))
    val MOSSY_GRAY_BRICK_SLAB = register("mossy_gray_brick_slab", SlabBlock(FabricBlockSettings.copy(MOSSY_GRAY_BRICKS).mapColor(DyeColor.GRAY)))
    val MOSSY_GRAY_BRICK_WALL = register("mossy_gray_brick_wall", WallBlock(FabricBlockSettings.copy(Blocks.BRICK_WALL).mapColor(DyeColor.GRAY)))

    val MOSSY_LIGHT_GRAY_BRICKS = register("mossy_light_gray_bricks", Block(FabricBlockSettings.copy(Blocks.BRICKS).mapColor(DyeColor.LIGHT_GRAY)))
    val MOSSY_LIGHT_GRAY_BRICK_STAIRS = register("mossy_light_gray_brick_stairs", StairsBlock(MOSSY_LIGHT_GRAY_BRICKS.defaultState, FabricBlockSettings.copy(MOSSY_LIGHT_GRAY_BRICKS).mapColor(DyeColor.LIGHT_GRAY)))
    val MOSSY_LIGHT_GRAY_BRICK_SLAB = register("mossy_light_gray_brick_slab", SlabBlock(FabricBlockSettings.copy(MOSSY_LIGHT_GRAY_BRICKS).mapColor(DyeColor.LIGHT_GRAY)))
    val MOSSY_LIGHT_GRAY_BRICK_WALL = register("mossy_light_gray_brick_wall", WallBlock(FabricBlockSettings.copy(Blocks.BRICK_WALL).mapColor(DyeColor.LIGHT_GRAY)))

    val MOSSY_CYAN_BRICKS = register("mossy_cyan_bricks", Block(FabricBlockSettings.copy(Blocks.BRICKS).mapColor(DyeColor.CYAN)))
    val MOSSY_CYAN_BRICK_STAIRS = register("mossy_cyan_brick_stairs", StairsBlock(MOSSY_CYAN_BRICKS.defaultState, FabricBlockSettings.copy(MOSSY_CYAN_BRICKS).mapColor(DyeColor.CYAN)))
    val MOSSY_CYAN_BRICK_SLAB = register("mossy_cyan_brick_slab", SlabBlock(FabricBlockSettings.copy(MOSSY_CYAN_BRICKS).mapColor(DyeColor.CYAN)))
    val MOSSY_CYAN_BRICK_WALL = register("mossy_cyan_brick_wall", WallBlock(FabricBlockSettings.copy(Blocks.BRICK_WALL).mapColor(DyeColor.CYAN)))

    val MOSSY_PURPLE_BRICKS = register("mossy_purple_bricks", Block(FabricBlockSettings.copy(Blocks.BRICKS).mapColor(DyeColor.PURPLE)))
    val MOSSY_PURPLE_BRICK_STAIRS = register("mossy_purple_brick_stairs", StairsBlock(MOSSY_PURPLE_BRICKS.defaultState, FabricBlockSettings.copy(MOSSY_PURPLE_BRICKS).mapColor(DyeColor.PURPLE)))
    val MOSSY_PURPLE_BRICK_SLAB = register("mossy_purple_brick_slab", SlabBlock(FabricBlockSettings.copy(MOSSY_PURPLE_BRICKS).mapColor(DyeColor.PURPLE)))
    val MOSSY_PURPLE_BRICK_WALL = register("mossy_purple_brick_wall", WallBlock(FabricBlockSettings.copy(Blocks.BRICK_WALL).mapColor(DyeColor.PURPLE)))

    val MOSSY_BLUE_BRICKS = register("mossy_blue_bricks", Block(FabricBlockSettings.copy(Blocks.BRICKS).mapColor(DyeColor.BLUE)))
    val MOSSY_BLUE_BRICK_STAIRS = register("mossy_blue_brick_stairs", StairsBlock(MOSSY_BLUE_BRICKS.defaultState, FabricBlockSettings.copy(MOSSY_BLUE_BRICKS).mapColor(DyeColor.BLUE)))
    val MOSSY_BLUE_BRICK_SLAB = register("mossy_blue_brick_slab", SlabBlock(FabricBlockSettings.copy(MOSSY_BLUE_BRICKS).mapColor(DyeColor.BLUE)))
    val MOSSY_BLUE_BRICK_WALL = register("mossy_blue_brick_wall", WallBlock(FabricBlockSettings.copy(Blocks.BRICK_WALL).mapColor(DyeColor.BLUE)))

    val MOSSY_BROWN_BRICKS = register("mossy_brown_bricks", Block(FabricBlockSettings.copy(Blocks.BRICKS).mapColor(DyeColor.BROWN)))
    val MOSSY_BROWN_BRICK_STAIRS = register("mossy_brown_brick_stairs", StairsBlock(MOSSY_BROWN_BRICKS.defaultState, FabricBlockSettings.copy(MOSSY_BROWN_BRICKS).mapColor(DyeColor.BROWN)))
    val MOSSY_BROWN_BRICK_SLAB = register("mossy_brown_brick_slab", SlabBlock(FabricBlockSettings.copy(MOSSY_BROWN_BRICKS).mapColor(DyeColor.BROWN)))
    val MOSSY_BROWN_BRICK_WALL = register("mossy_brown_brick_wall", WallBlock(FabricBlockSettings.copy(Blocks.BRICK_WALL).mapColor(DyeColor.BROWN)))

    val MOSSY_GREEN_BRICKS = register("mossy_green_bricks", Block(FabricBlockSettings.copy(Blocks.BRICKS).mapColor(DyeColor.GREEN)))
    val MOSSY_GREEN_BRICK_STAIRS = register("mossy_green_brick_stairs", StairsBlock(MOSSY_GREEN_BRICKS.defaultState, FabricBlockSettings.copy(MOSSY_GREEN_BRICKS).mapColor(DyeColor.GREEN)))
    val MOSSY_GREEN_BRICK_SLAB = register("mossy_green_brick_slab", SlabBlock(FabricBlockSettings.copy(MOSSY_GREEN_BRICKS).mapColor(DyeColor.GREEN)))
    val MOSSY_GREEN_BRICK_WALL = register("mossy_green_brick_wall", WallBlock(FabricBlockSettings.copy(Blocks.BRICK_WALL).mapColor(DyeColor.GREEN)))

    val MOSSY_RED_BRICKS = register("mossy_red_bricks", Block(FabricBlockSettings.copy(Blocks.BRICKS).mapColor(DyeColor.RED)))
    val MOSSY_RED_BRICK_STAIRS = register("mossy_red_brick_stairs", StairsBlock(MOSSY_RED_BRICKS.defaultState, FabricBlockSettings.copy(MOSSY_RED_BRICKS).mapColor(DyeColor.RED)))
    val MOSSY_RED_BRICK_SLAB = register("mossy_red_brick_slab", SlabBlock(FabricBlockSettings.copy(MOSSY_RED_BRICKS).mapColor(DyeColor.RED)))
    val MOSSY_RED_BRICK_WALL = register("mossy_red_brick_wall", WallBlock(FabricBlockSettings.copy(Blocks.BRICK_WALL).mapColor(DyeColor.RED)))

    val MOSSY_BLACK_BRICKS = register("mossy_black_bricks", Block(FabricBlockSettings.copy(Blocks.BRICKS).mapColor(DyeColor.BLACK)))
    val MOSSY_BLACK_BRICK_STAIRS = register("mossy_black_brick_stairs", StairsBlock(MOSSY_BLACK_BRICKS.defaultState, FabricBlockSettings.copy(MOSSY_BLACK_BRICKS).mapColor(DyeColor.BLACK)))
    val MOSSY_BLACK_BRICK_SLAB = register("mossy_black_brick_slab", SlabBlock(FabricBlockSettings.copy(MOSSY_BLACK_BRICKS).mapColor(DyeColor.BLACK)))
    val MOSSY_BLACK_BRICK_WALL = register("mossy_black_brick_wall", WallBlock(FabricBlockSettings.copy(Blocks.BRICK_WALL).mapColor(DyeColor.BLACK)))

    //endregion

    // region Aquarium Glass
    val CLEAR_GLASS = register("clear_glass", GlassBlock(FabricBlockSettings.copy(Blocks.GLASS)))
    val WHITE_STAINED_CLEAR_GLASS = register("white_stained_clear_glass", StainedGlassBlock(DyeColor.WHITE, FabricBlockSettings.copy(Blocks.WHITE_STAINED_GLASS)))
    val ORANGE_STAINED_CLEAR_GLASS = register("orange_stained_clear_glass", StainedGlassBlock(DyeColor.ORANGE, FabricBlockSettings.copy(Blocks.ORANGE_STAINED_GLASS)))
    val MAGENTA_STAINED_CLEAR_GLASS = register("magenta_stained_clear_glass", StainedGlassBlock(DyeColor.MAGENTA, FabricBlockSettings.copy(Blocks.MAGENTA_STAINED_GLASS)))
    val LIGHT_BLUE_STAINED_CLEAR_GLASS = register("light_blue_stained_clear_glass", StainedGlassBlock(DyeColor.LIGHT_BLUE, FabricBlockSettings.copy(Blocks.LIGHT_BLUE_STAINED_GLASS)))
    val YELLOW_STAINED_CLEAR_GLASS = register("yellow_stained_clear_glass", StainedGlassBlock(DyeColor.YELLOW, FabricBlockSettings.copy(Blocks.YELLOW_STAINED_GLASS)))
    val LIME_STAINED_CLEAR_GLASS = register("lime_stained_clear_glass", StainedGlassBlock(DyeColor.LIME, FabricBlockSettings.copy(Blocks.LIME_STAINED_GLASS)))
    val PINK_STAINED_CLEAR_GLASS = register("pink_stained_clear_glass", StainedGlassBlock(DyeColor.PINK, FabricBlockSettings.copy(Blocks.PINK_STAINED_GLASS)))
    val GRAY_STAINED_CLEAR_GLASS = register("gray_stained_clear_glass", StainedGlassBlock(DyeColor.GRAY, FabricBlockSettings.copy(Blocks.GRAY_STAINED_GLASS)))
    val LIGHT_GRAY_STAINED_CLEAR_GLASS = register("light_gray_stained_clear_glass", StainedGlassBlock(DyeColor.LIGHT_GRAY, FabricBlockSettings.copy(Blocks.LIGHT_GRAY_STAINED_GLASS)))
    val CYAN_STAINED_CLEAR_GLASS = register("cyan_stained_clear_glass", StainedGlassBlock(DyeColor.CYAN, FabricBlockSettings.copy(Blocks.CYAN_STAINED_GLASS)))
    val PURPLE_STAINED_CLEAR_GLASS = register("purple_stained_clear_glass", StainedGlassBlock(DyeColor.PURPLE, FabricBlockSettings.copy(Blocks.PURPLE_STAINED_GLASS)))
    val BLUE_STAINED_CLEAR_GLASS = register("blue_stained_clear_glass", StainedGlassBlock(DyeColor.BLUE, FabricBlockSettings.copy(Blocks.BLUE_STAINED_GLASS)))
    val BROWN_STAINED_CLEAR_GLASS = register("brown_stained_clear_glass", StainedGlassBlock(DyeColor.BROWN, FabricBlockSettings.copy(Blocks.BROWN_STAINED_GLASS)))
    val GREEN_STAINED_CLEAR_GLASS = register("green_stained_clear_glass", StainedGlassBlock(DyeColor.GREEN, FabricBlockSettings.copy(Blocks.GREEN_STAINED_GLASS)))
    val RED_STAINED_CLEAR_GLASS = register("red_stained_clear_glass", StainedGlassBlock(DyeColor.RED, FabricBlockSettings.copy(Blocks.RED_STAINED_GLASS)))
    val BLACK_STAINED_CLEAR_GLASS = register("black_stained_clear_glass", StainedGlassBlock(DyeColor.BLACK, FabricBlockSettings.copy(Blocks.BLACK_STAINED_GLASS)))

    val CLEAR_GLASS_PANE = register("clear_glass_pane", PaneBlock(FabricBlockSettings.copy(Blocks.GLASS_PANE)))
    val WHITE_STAINED_CLEAR_GLASS_PANE = register("white_stained_clear_glass_pane", StainedGlassPaneBlock(DyeColor.WHITE, FabricBlockSettings.copy(Blocks.WHITE_STAINED_GLASS_PANE)))
    val ORANGE_STAINED_CLEAR_GLASS_PANE = register("orange_stained_clear_glass_pane", StainedGlassPaneBlock(DyeColor.ORANGE, FabricBlockSettings.copy(Blocks.ORANGE_STAINED_GLASS_PANE)))
    val MAGENTA_STAINED_CLEAR_GLASS_PANE = register("magenta_stained_clear_glass_pane", StainedGlassPaneBlock(DyeColor.MAGENTA, FabricBlockSettings.copy(Blocks.MAGENTA_STAINED_GLASS_PANE)))
    val LIGHT_BLUE_STAINED_CLEAR_GLASS_PANE = register("light_blue_stained_clear_glass_pane", StainedGlassPaneBlock(DyeColor.LIGHT_BLUE, FabricBlockSettings.copy(Blocks.LIGHT_BLUE_STAINED_GLASS_PANE)))
    val YELLOW_STAINED_CLEAR_GLASS_PANE = register("yellow_stained_clear_glass_pane", StainedGlassPaneBlock(DyeColor.YELLOW, FabricBlockSettings.copy(Blocks.YELLOW_STAINED_GLASS_PANE)))
    val LIME_STAINED_CLEAR_GLASS_PANE = register("lime_stained_clear_glass_pane", StainedGlassPaneBlock(DyeColor.LIME, FabricBlockSettings.copy(Blocks.LIME_STAINED_GLASS_PANE)))
    val PINK_STAINED_CLEAR_GLASS_PANE = register("pink_stained_clear_glass_pane", StainedGlassPaneBlock(DyeColor.PINK, FabricBlockSettings.copy(Blocks.PINK_STAINED_GLASS_PANE)))
    val GRAY_STAINED_CLEAR_GLASS_PANE = register("gray_stained_clear_glass_pane", StainedGlassPaneBlock(DyeColor.GRAY, FabricBlockSettings.copy(Blocks.GRAY_STAINED_GLASS_PANE)))
    val LIGHT_GRAY_STAINED_CLEAR_GLASS_PANE = register("light_gray_stained_clear_glass_pane", StainedGlassPaneBlock(DyeColor.LIGHT_GRAY, FabricBlockSettings.copy(Blocks.LIGHT_GRAY_STAINED_GLASS_PANE)))
    val CYAN_STAINED_CLEAR_GLASS_PANE = register("cyan_stained_clear_glass_pane", StainedGlassPaneBlock(DyeColor.CYAN, FabricBlockSettings.copy(Blocks.CYAN_STAINED_GLASS_PANE)))
    val PURPLE_STAINED_CLEAR_GLASS_PANE = register("purple_stained_clear_glass_pane", StainedGlassPaneBlock(DyeColor.PURPLE, FabricBlockSettings.copy(Blocks.PURPLE_STAINED_GLASS_PANE)))
    val BLUE_STAINED_CLEAR_GLASS_PANE = register("blue_stained_clear_glass_pane", StainedGlassPaneBlock(DyeColor.BLUE, FabricBlockSettings.copy(Blocks.BLUE_STAINED_GLASS_PANE)))
    val BROWN_STAINED_CLEAR_GLASS_PANE = register("brown_stained_clear_glass_pane", StainedGlassPaneBlock(DyeColor.BROWN, FabricBlockSettings.copy(Blocks.BROWN_STAINED_GLASS_PANE)))
    val GREEN_STAINED_CLEAR_GLASS_PANE = register("green_stained_clear_glass_pane", StainedGlassPaneBlock(DyeColor.GREEN, FabricBlockSettings.copy(Blocks.GREEN_STAINED_GLASS_PANE)))
    val RED_STAINED_CLEAR_GLASS_PANE = register("red_stained_clear_glass_pane", StainedGlassPaneBlock(DyeColor.RED, FabricBlockSettings.copy(Blocks.RED_STAINED_GLASS_PANE)))
    val BLACK_STAINED_CLEAR_GLASS_PANE = register("black_stained_clear_glass_pane", StainedGlassPaneBlock(DyeColor.BLACK, FabricBlockSettings.copy(Blocks.BLACK_STAINED_GLASS_PANE)))

    // endregion

    private fun register(id: String, block: Block): Block {
        return Registry.register(Registries.BLOCK, Identifier(HybridBlocks.MOD_ID, id), block)
    }
}
