plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev.legacyforge'
    id 'org.jetbrains.kotlin.jvm'
}

legacyForge {
    validateAccessTransformers = false
    mcpVersion = minecraft_version
    accessTransformers = [project(':common').file("src/main/resources/META-INF/accesstransformer.cfg")]
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
}

repositories {
    mavenCentral()
}

configurations{
    commonJava
}

configurations.create('commonJavaOut')
dependencies {
    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.5.0"))
    implementation(jarJar("io.github.llamalad7:mixinextras-forge:0.5.0"))
    implementation 'org.jetbrains:annotations:25.0.0'

    //We load the Forge version of any included mod dependencies
    commonJavaOut files("src/main/java/")
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }

    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'org.jetbrains.kotlin.jvm'
    apply plugin: 'kotlin'


    repositories {
        mavenCentral()
    }

    compileKotlin {
        if (file("src/main/resources/META-INF/accesstransformer.cfg").exists()) {
            accessTransformers = ["src/main/resources/META-INF/accesstransformer.cfg"]
        }
        source(project(":common").sourceSets.main.allSource)
        inputs.file "../gradle.properties"
    }
}