plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev'
    id 'org.jetbrains.kotlin.jvm'
}

neoForge {
    neoFormVersion = neo_form_version
    // Automatically enable AccessTransformers if the file exists
    def at = file("src/main/resources/META-INF/accesstransformer.cfg")
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
}

repositories {
    maven {
        name = "Jitpack"
        url = "https://jitpack.io/"
    }

    maven {
        name = "Debug Utils (GitLab)"
        url = "https://gitlab.com/api/v4/projects/21830712/packages/maven/"
    }
}

dependencies {
    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.5.0"))
    implementation(jarJar("io.github.llamalad7:mixinextras-forge:0.5.0"))
    implementation 'org.jetbrains:annotations:25.0.0'
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }

    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}
